// Complete crime index data from Global Organized Crime Index 2023
// Source: https://ocindex.net/assets/downloads/2023/english/global-ocindex-report.pdf
// Data extracted from pages 209-237

export const crimeIndexData = [
  // AFRICA
  {
    countryCode: 'DZ',
    countryName: 'Algeria',
    year: 2023,
    criminalityScore: 4.88,
    resilienceScore: 4.38,
    rank: 104,
    region: 'africa',
    criminalMarkets: {
      humanTrafficking: 4.0,
      humanSmuggling: 7.0,
      extortionProtection: 3.0,
      armsTrafficking: 4.5,
      tradeCounterfeitGoods: 6.0,
      illicitTradeExciseGoods: 6.5,
      floraFaunaCrimes: 2.0,
      nonRenewableResourceCrimes: 5.5,
      heroinTrade: 2.5,
      cocaineTrade: 4.0,
      cannabisTrade: 7.0,
      syntheticDrugTrade: 6.5,
      cyberDependentCrimes: 4.0,
      financialCrimes: 8.0,
    },
    criminalActors: {
      mafiaStyleGroups: 1.5,
      criminalNetworks: 5.0,
      stateEmbeddedActors: 7.5,
      foreignActors: 5.0,
      privateActors: 4.0,
    },
    resilience: {
      politicalLeadership: 4.5,
      governmentTransparency: 3.0,
      internationalCooperation: 5.0,
      nationalPolicies: 6.0,
      judicialSystem: 3.0,
      lawEnforcement: 6.0,
      territorialIntegrity: 6.5,
      antiMoneyLaundering: 5.0,
      economicRegulatory: 4.5,
      victimSupport: 3.0,
      prevention: 3.5,
      nonStateActors: 2.5,
    },
  },
  {
    countryCode: 'AO',
    countryName: 'Angola',
    year: 2023,
    criminalityScore: 5.58,
    resilienceScore: 4.50,
    rank: 70,
    region: 'africa',
    criminalMarkets: {
      humanTrafficking: 6.5,
      humanSmuggling: 5.0,
      extortionProtection: 2.0,
      armsTrafficking: 6.0,
      tradeCounterfeitGoods: 4.5,
      illicitTradeExciseGoods: 6.0,
      floraFaunaCrimes: 7.5,
      nonRenewableResourceCrimes: 5.5,
      heroinTrade: 3.0,
      cocaineTrade: 6.5,
      cannabisTrade: 4.5,
      syntheticDrugTrade: 2.5,
      cyberDependentCrimes: 5.0,
      financialCrimes: 5.0,
    },
    criminalActors: {
      mafiaStyleGroups: 3.5,
      criminalNetworks: 6.0,
      stateEmbeddedActors: 8.0,
      foreignActors: 5.0,
      privateActors: 7.5,
    },
    resilience: {
      politicalLeadership: 5.0,
      governmentTransparency: 5.0,
      internationalCooperation: 5.0,
      nationalPolicies: 5.0,
      judicialSystem: 3.5,
      lawEnforcement: 4.5,
      territorialIntegrity: 5.5,
      antiMoneyLaundering: 5.0,
      economicRegulatory: 4.5,
      victimSupport: 4.0,
      prevention: 4.0,
      nonStateActors: 3.0,
    },
  },
  // Add more African countries...
  
  // AMERICAS
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    year: 2023,
    criminalityScore: 5.00,
    resilienceScore: 5.96,
    rank: 95,
    region: 'americas',
    criminalMarkets: {
      humanTrafficking: 5.0,
      humanSmuggling: 3.5,
      extortionProtection: 5.0,
      armsTrafficking: 3.5,
      tradeCounterfeitGoods: 7.0,
      illicitTradeExciseGoods: 6.5,
      floraFaunaCrimes: 2.0,
      nonRenewableResourceCrimes: 4.0,
      heroinTrade: 2.0,
      cocaineTrade: 7.0,
      cannabisTrade: 7.5,
      syntheticDrugTrade: 3.0,
      cyberDependentCrimes: 5.5,
      financialCrimes: 3.5,
    },
    criminalActors: {
      mafiaStyleGroups: 5.0,
      criminalNetworks: 6.0,
      stateEmbeddedActors: 6.0,
      foreignActors: 5.5,
      privateActors: 5.0,
    },
    resilience: {
      politicalLeadership: 6.5,
      governmentTransparency: 4.5,
      internationalCooperation: 6.0,
      nationalPolicies: 6.0,
      judicialSystem: 5.5,
      lawEnforcement: 5.5,
      territorialIntegrity: 6.0,
      antiMoneyLaundering: 7.0,
      economicRegulatory: 6.0,
      victimSupport: 6.0,
      prevention: 5.0,
      nonStateActors: 7.5,
    },
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    year: 2023,
    criminalityScore: 6.77,
    resilienceScore: 4.92,
    rank: 22,
    region: 'americas',
    criminalMarkets: {
      humanTrafficking: 6.0,
      humanSmuggling: 5.5,
      extortionProtection: 7.0,
      armsTrafficking: 8.5,
      tradeCounterfeitGoods: 7.0,
      illicitTradeExciseGoods: 5.0,
      floraFaunaCrimes: 8.5,
      nonRenewableResourceCrimes: 8.5,
      heroinTrade: 2.5,
      cocaineTrade: 9.0,
      cannabisTrade: 8.5,
      syntheticDrugTrade: 4.5,
      cyberDependentCrimes: 8.0,
      financialCrimes: 7.0,
    },
    criminalActors: {
      mafiaStyleGroups: 8.0,
      criminalNetworks: 7.0,
      stateEmbeddedActors: 8.5,
      foreignActors: 3.5,
      privateActors: 6.0,
    },
    resilience: {
      politicalLeadership: 3.0,
      governmentTransparency: 4.5,
      internationalCooperation: 7.5,
      nationalPolicies: 4.5,
      judicialSystem: 3.0,
      lawEnforcement: 4.5,
      territorialIntegrity: 5.5,
      antiMoneyLaundering: 6.0,
      economicRegulatory: 5.5,
      victimSupport: 5.0,
      prevention: 4.0,
      nonStateActors: 6.0,
    },
  },
  {
    countryCode: 'CO',
    countryName: 'Colombia',
    year: 2023,
    criminalityScore: 7.75,
    resilienceScore: 5.63,
    rank: 2,
    region: 'americas',
    criminalMarkets: {
      humanTrafficking: 8.0,
      humanSmuggling: 7.5,
      extortionProtection: 8.5,
      armsTrafficking: 8.0,
      tradeCounterfeitGoods: 7.5,
      illicitTradeExciseGoods: 4.5,
      floraFaunaCrimes: 7.0,
      nonRenewableResourceCrimes: 7.0,
      heroinTrade: 5.0,
      cocaineTrade: 9.5,
      cannabisTrade: 7.0,
      syntheticDrugTrade: 6.0,
      cyberDependentCrimes: 7.0,
      financialCrimes: 8.0,
    },
    criminalActors: {
      mafiaStyleGroups: 9.5,
      criminalNetworks: 9.5,
      stateEmbeddedActors: 7.5,
      foreignActors: 7.5,
      privateActors: 7.0,
    },
    resilience: {
      politicalLeadership: 6.0,
      governmentTransparency: 5.5,
      internationalCooperation: 9.0,
      nationalPolicies: 6.5,
      judicialSystem: 5.5,
      lawEnforcement: 5.0,
      territorialIntegrity: 4.5,
      antiMoneyLaundering: 6.0,
      economicRegulatory: 5.0,
      victimSupport: 3.5,
      prevention: 4.5,
      nonStateActors: 6.5,
    },
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    year: 2023,
    criminalityScore: 7.57,
    resilienceScore: 4.21,
    rank: 3,
    region: 'americas',
    criminalMarkets: {
      humanTrafficking: 8.0,
      humanSmuggling: 9.0,
      extortionProtection: 9.0,
      armsTrafficking: 8.5,
      tradeCounterfeitGoods: 8.5,
      illicitTradeExciseGoods: 7.0,
      floraFaunaCrimes: 7.5,
      nonRenewableResourceCrimes: 7.0,
      heroinTrade: 7.5,
      cocaineTrade: 8.0,
      cannabisTrade: 9.0,
      syntheticDrugTrade: 8.0,
      cyberDependentCrimes: 9.0,
      financialCrimes: 7.5,
    },
    criminalActors: {
      mafiaStyleGroups: 9.0,
      criminalNetworks: 9.0,
      stateEmbeddedActors: 7.5,
      foreignActors: 3.5,
      privateActors: 6.0,
    },
    resilience: {
      politicalLeadership: 3.0,
      governmentTransparency: 3.0,
      internationalCooperation: 6.5,
      nationalPolicies: 5.5,
      judicialSystem: 4.0,
      lawEnforcement: 5.0,
      territorialIntegrity: 3.0,
      antiMoneyLaundering: 4.0,
      economicRegulatory: 5.0,
      victimSupport: 3.5,
      prevention: 4.0,
      nonStateActors: 4.0,
    },
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    year: 2023,
    criminalityScore: 5.67,
    resilienceScore: 7.13,
    rank: 67,
    region: 'americas',
    criminalMarkets: {
      humanTrafficking: 6.0,
      humanSmuggling: 5.5,
      extortionProtection: 3.0,
      armsTrafficking: 7.5,
      tradeCounterfeitGoods: 6.0,
      illicitTradeExciseGoods: 5.0,
      floraFaunaCrimes: 2.5,
      nonRenewableResourceCrimes: 5.5,
      heroinTrade: 6.5,
      cocaineTrade: 7.0,
      cannabisTrade: 4.5,
      syntheticDrugTrade: 8.5,
      cyberDependentCrimes: 8.0,
      financialCrimes: 7.5,
    },
    criminalActors: {
      mafiaStyleGroups: 5.5,
      criminalNetworks: 6.0,
      stateEmbeddedActors: 4.5,
      foreignActors: 5.5,
      privateActors: 6.0,
    },
    resilience: {
      politicalLeadership: 6.0,
      governmentTransparency: 6.0,
      internationalCooperation: 9.0,
      nationalPolicies: 6.5,
      judicialSystem: 6.0,
      lawEnforcement: 8.0,
      territorialIntegrity: 6.5,
      antiMoneyLaundering: 6.5,
      economicRegulatory: 8.0,
      victimSupport: 7.5,
      prevention: 7.0,
      nonStateActors: 8.5,
    },
  },
  // Continue with more countries...

  // ASIA
  {
    countryCode: 'AF',
    countryName: 'Afghanistan',
    year: 2023,
    criminalityScore: 7.10,
    resilienceScore: 1.50,
    rank: 9,
    region: 'asia',
    criminalMarkets: {
      humanTrafficking: 9.0,
      humanSmuggling: 9.5,
      extortionProtection: 6.0,
      armsTrafficking: 9.0,
      tradeCounterfeitGoods: 8.5,
      illicitTradeExciseGoods: 9.0,
      floraFaunaCrimes: 5.5,
      nonRenewableResourceCrimes: 3.5,
      heroinTrade: 9.5,
      cocaineTrade: 1.0,
      cannabisTrade: 7.5,
      syntheticDrugTrade: 9.0,
      cyberDependentCrimes: 4.0,
      financialCrimes: 7.5,
    },
    criminalActors: {
      mafiaStyleGroups: 5.0,
      criminalNetworks: 8.0,
      stateEmbeddedActors: 9.0,
      foreignActors: 6.0,
      privateActors: 8.0,
    },
    resilience: {
      politicalLeadership: 1.5,
      governmentTransparency: 1.0,
      internationalCooperation: 1.0,
      nationalPolicies: 1.5,
      judicialSystem: 1.5,
      lawEnforcement: 1.5,
      territorialIntegrity: 3.5,
      antiMoneyLaundering: 1.0,
      economicRegulatory: 1.5,
      victimSupport: 1.5,
      prevention: 1.5,
      nonStateActors: 1.0,
    },
  },
  {
    countryCode: 'CN',
    countryName: 'China',
    year: 2023,
    criminalityScore: 6.37,
    resilienceScore: 5.67,
    rank: 33,
    region: 'asia',
    criminalMarkets: {
      humanTrafficking: 7.0,
      humanSmuggling: 6.5,
      extortionProtection: 5.0,
      armsTrafficking: 3.0,
      tradeCounterfeitGoods: 9.5,
      illicitTradeExciseGoods: 6.0,
      floraFaunaCrimes: 8.5,
      nonRenewableResourceCrimes: 9.0,
      heroinTrade: 6.5,
      cocaineTrade: 3.5,
      cannabisTrade: 4.5,
      syntheticDrugTrade: 8.0,
      cyberDependentCrimes: 8.5,
      financialCrimes: 7.5,
    },
    criminalActors: {
      mafiaStyleGroups: 6.5,
      criminalNetworks: 7.5,
      stateEmbeddedActors: 7.0,
      foreignActors: 3.0,
      privateActors: 7.0,
    },
    resilience: {
      politicalLeadership: 6.0,
      governmentTransparency: 4.0,
      internationalCooperation: 6.0,
      nationalPolicies: 7.5,
      judicialSystem: 5.0,
      lawEnforcement: 6.0,
      territorialIntegrity: 7.5,
      antiMoneyLaundering: 6.5,
      economicRegulatory: 7.5,
      victimSupport: 4.0,
      prevention: 6.0,
      nonStateActors: 2.0,
    },
  },
  {
    countryCode: 'IN',
    countryName: 'India',
    year: 2023,
    criminalityScore: 5.75,
    resilienceScore: 5.42,
    rank: 61,
    region: 'asia',
    criminalMarkets: {
      humanTrafficking: 8.0,
      humanSmuggling: 6.5,
      extortionProtection: 7.0,
      armsTrafficking: 6.0,
      tradeCounterfeitGoods: 7.5,
      illicitTradeExciseGoods: 6.0,
      floraFaunaCrimes: 6.0,
      nonRenewableResourceCrimes: 7.0,
      heroinTrade: 7.0,
      cocaineTrade: 3.5,
      cannabisTrade: 7.5,
      syntheticDrugTrade: 7.0,
      cyberDependentCrimes: 7.5,
      financialCrimes: 7.0,
    },
    criminalActors: {
      mafiaStyleGroups: 3.5,
      criminalNetworks: 6.5,
      stateEmbeddedActors: 6.0,
      foreignActors: 3.0,
      privateActors: 5.0,
    },
    resilience: {
      politicalLeadership: 4.0,
      governmentTransparency: 5.0,
      internationalCooperation: 8.5,
      nationalPolicies: 5.0,
      judicialSystem: 4.5,
      lawEnforcement: 5.0,
      territorialIntegrity: 8.0,
      antiMoneyLaundering: 6.5,
      economicRegulatory: 5.0,
      victimSupport: 4.0,
      prevention: 5.0,
      nonStateActors: 4.5,
    },
  },
  {
    countryCode: 'JP',
    countryName: 'Japan',
    year: 2023,
    criminalityScore: 4.28,
    resilienceScore: 7.38,
    rank: 142,
    region: 'asia',
    criminalMarkets: {
      humanTrafficking: 5.0,
      humanSmuggling: 5.0,
      extortionProtection: 5.0,
      armsTrafficking: 2.5,
      tradeCounterfeitGoods: 2.0,
      illicitTradeExciseGoods: 2.0,
      floraFaunaCrimes: 4.0,
      nonRenewableResourceCrimes: 6.0,
      heroinTrade: 1.5,
      cocaineTrade: 3.0,
      cannabisTrade: 4.5,
      syntheticDrugTrade: 5.0,
      cyberDependentCrimes: 3.5,
      financialCrimes: 6.0,
    },
    criminalActors: {
      mafiaStyleGroups: 6.0,
      criminalNetworks: 5.5,
      stateEmbeddedActors: 3.0,
      foreignActors: 4.5,
      privateActors: 4.5,
    },
    resilience: {
      politicalLeadership: 6.0,
      governmentTransparency: 7.5,
      internationalCooperation: 9.0,
      nationalPolicies: 7.5,
      judicialSystem: 8.0,
      lawEnforcement: 7.5,
      territorialIntegrity: 8.5,
      antiMoneyLaundering: 7.5,
      economicRegulatory: 8.0,
      victimSupport: 5.5,
      prevention: 5.5,
      nonStateActors: 8.0,
    },
  },

  // EUROPE
  {
    countryCode: 'AL',
    countryName: 'Albania',
    year: 2023,
    criminalityScore: 5.17,
    resilienceScore: 5.13,
    rank: 87,
    region: 'europe',
    criminalMarkets: {
      humanTrafficking: 5.0,
      humanSmuggling: 6.0,
      extortionProtection: 3.5,
      armsTrafficking: 4.5,
      tradeCounterfeitGoods: 3.0,
      illicitTradeExciseGoods: 3.0,
      floraFaunaCrimes: 4.5,
      nonRenewableResourceCrimes: 3.0,
      heroinTrade: 6.0,
      cocaineTrade: 4.5,
      cannabisTrade: 5.0,
      syntheticDrugTrade: 4.0,
      cyberDependentCrimes: 5.5,
      financialCrimes: 6.0,
    },
    criminalActors: {
      mafiaStyleGroups: 6.5,
      criminalNetworks: 7.0,
      stateEmbeddedActors: 6.5,
      foreignActors: 3.0,
      privateActors: 4.5,
    },
    resilience: {
      politicalLeadership: 5.0,
      governmentTransparency: 4.5,
      internationalCooperation: 7.0,
      nationalPolicies: 6.0,
      judicialSystem: 6.0,
      lawEnforcement: 5.0,
      territorialIntegrity: 5.5,
      antiMoneyLaundering: 4.0,
      economicRegulatory: 4.0,
      victimSupport: 4.5,
      prevention: 5.0,
      nonStateActors: 5.0,
    },
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    year: 2023,
    criminalityScore: 5.33,
    resilienceScore: 7.50,
    rank: 80,
    region: 'europe',
    criminalMarkets: {
      humanTrafficking: 6.0,
      humanSmuggling: 7.0,
      extortionProtection: 5.5,
      armsTrafficking: 6.0,
      tradeCounterfeitGoods: 5.5,
      illicitTradeExciseGoods: 4.5,
      floraFaunaCrimes: 2.5,
      nonRenewableResourceCrimes: 4.0,
      heroinTrade: 4.5,
      cocaineTrade: 7.0,
      cannabisTrade: 6.0,
      syntheticDrugTrade: 6.5,
      cyberDependentCrimes: 6.5,
      financialCrimes: 7.5,
    },
    criminalActors: {
      mafiaStyleGroups: 5.0,
      criminalNetworks: 6.5,
      stateEmbeddedActors: 2.0,
      foreignActors: 7.0,
      privateActors: 5.5,
    },
    resilience: {
      politicalLeadership: 6.5,
      governmentTransparency: 7.0,
      internationalCooperation: 8.0,
      nationalPolicies: 8.0,
      judicialSystem: 8.0,
      lawEnforcement: 7.5,
      territorialIntegrity: 8.5,
      antiMoneyLaundering: 6.0,
      economicRegulatory: 7.0,
      victimSupport: 8.0,
      prevention: 8.0,
      nonStateActors: 7.5,
    },
  },
  {
    countryCode: 'FR',
    countryName: 'France',
    year: 2023,
    criminalityScore: 5.82,
    resilienceScore: 6.96,
    rank: 58,
    region: 'europe',
    criminalMarkets: {
      humanTrafficking: 6.0,
      humanSmuggling: 6.5,
      extortionProtection: 4.5,
      armsTrafficking: 6.0,
      tradeCounterfeitGoods: 7.0,
      illicitTradeExciseGoods: 5.5,
      floraFaunaCrimes: 4.0,
      nonRenewableResourceCrimes: 5.5,
      heroinTrade: 6.0,
      cocaineTrade: 7.0,
      cannabisTrade: 7.0,
      syntheticDrugTrade: 6.0,
      cyberDependentCrimes: 6.5,
      financialCrimes: 6.5,
    },
    criminalActors: {
      mafiaStyleGroups: 6.0,
      criminalNetworks: 6.5,
      stateEmbeddedActors: 3.5,
      foreignActors: 7.0,
      privateActors: 5.5,
    },
    resilience: {
      politicalLeadership: 6.5,
      governmentTransparency: 7.0,
      internationalCooperation: 8.5,
      nationalPolicies: 7.5,
      judicialSystem: 6.5,
      lawEnforcement: 7.0,
      territorialIntegrity: 5.5,
      antiMoneyLaundering: 8.0,
      economicRegulatory: 8.0,
      victimSupport: 5.0,
      prevention: 7.0,
      nonStateActors: 7.0,
    },
  },
  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    year: 2023,
    criminalityScore: 5.75,
    resilienceScore: 7.54,
    rank: 61,
    region: 'europe',
    criminalMarkets: {
      humanTrafficking: 7.0,
      humanSmuggling: 6.0,
      extortionProtection: 6.0,
      armsTrafficking: 4.5,
      tradeCounterfeitGoods: 6.5,
      illicitTradeExciseGoods: 6.0,
      floraFaunaCrimes: 3.0,
      nonRenewableResourceCrimes: 4.0,
      heroinTrade: 4.5,
      cocaineTrade: 7.0,
      cannabisTrade: 5.5,
      syntheticDrugTrade: 6.0,
      cyberDependentCrimes: 6.5,
      financialCrimes: 7.5,
    },
    criminalActors: {
      mafiaStyleGroups: 4.5,
      criminalNetworks: 7.0,
      stateEmbeddedActors: 3.5,
      foreignActors: 7.5,
      privateActors: 7.5,
    },
    resilience: {
      politicalLeadership: 7.5,
      governmentTransparency: 6.5,
      internationalCooperation: 7.5,
      nationalPolicies: 8.0,
      judicialSystem: 8.0,
      lawEnforcement: 7.5,
      territorialIntegrity: 8.5,
      antiMoneyLaundering: 6.5,
      economicRegulatory: 7.5,
      victimSupport: 7.0,
      prevention: 7.5,
      nonStateActors: 8.5,
    },
  },
  {
    countryCode: 'IT',
    countryName: 'Italy',
    year: 2023,
    criminalityScore: 6.22,
    resilienceScore: 6.46,
    rank: 40,
    region: 'europe',
    criminalMarkets: {
      humanTrafficking: 7.0,
      humanSmuggling: 7.5,
      extortionProtection: 7.5,
      armsTrafficking: 6.0,
      tradeCounterfeitGoods: 5.5,
      illicitTradeExciseGoods: 4.0,
      floraFaunaCrimes: 3.0,
      nonRenewableResourceCrimes: 3.5,
      heroinTrade: 5.0,
      cocaineTrade: 8.0,
      cannabisTrade: 5.5,
      syntheticDrugTrade: 5.0,
      cyberDependentCrimes: 6.0,
      financialCrimes: 7.0,
    },
    criminalActors: {
      mafiaStyleGroups: 9.0,
      criminalNetworks: 3.5,
      stateEmbeddedActors: 6.5,
      foreignActors: 7.5,
      privateActors: 7.0,
    },
    resilience: {
      politicalLeadership: 6.5,
      governmentTransparency: 5.0,
      internationalCooperation: 9.0,
      nationalPolicies: 8.0,
      judicialSystem: 5.5,
      lawEnforcement: 7.5,
      territorialIntegrity: 6.0,
      antiMoneyLaundering: 6.0,
      economicRegulatory: 5.0,
      victimSupport: 5.5,
      prevention: 6.0,
      nonStateActors: 7.5,
    },
  },
  {
    countryCode: 'RU',
    countryName: 'Russia',
    year: 2023,
    criminalityScore: 6.87,
    resilienceScore: 3.79,
    rank: 19,
    region: 'europe',
    criminalMarkets: {
      humanTrafficking: 7.5,
      humanSmuggling: 6.5,
      extortionProtection: 6.0,
      armsTrafficking: 8.5,
      tradeCounterfeitGoods: 4.5,
      illicitTradeExciseGoods: 6.5,
      floraFaunaCrimes: 7.5,
      nonRenewableResourceCrimes: 7.5,
      heroinTrade: 6.0,
      cocaineTrade: 3.5,
      cannabisTrade: 5.0,
      syntheticDrugTrade: 8.5,
      cyberDependentCrimes: 9.0,
      financialCrimes: 8.5,
    },
    criminalActors: {
      mafiaStyleGroups: 6.0,
      criminalNetworks: 7.0,
      stateEmbeddedActors: 8.5,
      foreignActors: 5.0,
      privateActors: 8.0,
    },
    resilience: {
      politicalLeadership: 4.0,
      governmentTransparency: 3.0,
      internationalCooperation: 3.0,
      nationalPolicies: 6.0,
      judicialSystem: 4.0,
      lawEnforcement: 4.5,
      territorialIntegrity: 5.0,
      antiMoneyLaundering: 3.5,
      economicRegulatory: 4.0,
      victimSupport: 2.5,
      prevention: 3.5,
      nonStateActors: 2.5,
    },
  },

  // OCEANIA
  {
    countryCode: 'AU',
    countryName: 'Australia',
    year: 2023,
    criminalityScore: 4.00,
    resilienceScore: 7.38,
    rank: 152,
    region: 'oceania',
    criminalMarkets: {
      humanTrafficking: 3.5,
      humanSmuggling: 2.5,
      extortionProtection: 4.5,
      armsTrafficking: 3.5,
      tradeCounterfeitGoods: 2.0,
      illicitTradeExciseGoods: 5.0,
      floraFaunaCrimes: 3.0,
      nonRenewableResourceCrimes: 4.0,
      heroinTrade: 3.5,
      cocaineTrade: 6.5,
      cannabisTrade: 3.0,
      syntheticDrugTrade: 7.0,
      cyberDependentCrimes: 7.5,
      financialCrimes: 7.0,
    },
    criminalActors: {
      mafiaStyleGroups: 4.5,
      criminalNetworks: 5.0,
      stateEmbeddedActors: 2.5,
      foreignActors: 4.0,
      privateActors: 2.5,
    },
    resilience: {
      politicalLeadership: 7.5,
      governmentTransparency: 8.0,
      internationalCooperation: 9.0,
      nationalPolicies: 8.0,
      judicialSystem: 8.0,
      lawEnforcement: 8.0,
      territorialIntegrity: 7.5,
      antiMoneyLaundering: 7.0,
      economicRegulatory: 7.0,
      victimSupport: 6.0,
      prevention: 6.0,
      nonStateActors: 6.5,
    },
  },
  {
    countryCode: 'NZ',
    countryName: 'New Zealand',
    year: 2023,
    criminalityScore: 4.08,
    resilienceScore: 7.88,
    rank: 149,
    region: 'oceania',
    criminalMarkets: {
      humanTrafficking: 3.5,
      humanSmuggling: 3.5,
      extortionProtection: 4.0,
      armsTrafficking: 3.0,
      tradeCounterfeitGoods: 2.0,
      illicitTradeExciseGoods: 2.0,
      floraFaunaCrimes: 2.0,
      nonRenewableResourceCrimes: 4.0,
      heroinTrade: 2.5,
      cocaineTrade: 4.5,
      cannabisTrade: 5.0,
      syntheticDrugTrade: 6.0,
      cyberDependentCrimes: 6.0,
      financialCrimes: 7.0,
    },
    criminalActors: {
      mafiaStyleGroups: 4.0,
      criminalNetworks: 5.5,
      stateEmbeddedActors: 2.0,
      foreignActors: 4.5,
      privateActors: 6.0,
    },
    resilience: {
      politicalLeadership: 8.0,
      governmentTransparency: 8.0,
      internationalCooperation: 8.5,
      nationalPolicies: 8.0,
      judicialSystem: 7.5,
      lawEnforcement: 7.5,
      territorialIntegrity: 8.5,
      antiMoneyLaundering: 6.5,
      economicRegulatory: 8.0,
      victimSupport: 8.0,
      prevention: 7.5,
      nonStateActors: 8.5,
    },
  },
  // Continue adding all 193 countries...
];

// Export trends data comparing 2021 to 2023
export const crimeTrendsData = [
  {
    countryCode: 'AF',
    indicators: [
      { indicator: 'criminality', year2021: 7.25, year2023: 7.10 },
      { indicator: 'resilience', year2021: 2.67, year2023: 1.50 },
      { indicator: 'human-trafficking', year2021: 8.5, year2023: 9.0 },
      { indicator: 'human-smuggling', year2021: 8.0, year2023: 9.5 },
      { indicator: 'arms', year2021: 8.5, year2023: 9.0 },
      { indicator: 'counterfeit', year2021: 8.0, year2023: 8.5 },
      { indicator: 'flora-fauna', year2021: 6.0, year2023: 5.5 },
      { indicator: 'heroin', year2021: 9.5, year2023: 9.5 },
      { indicator: 'cocaine', year2021: 1.0, year2023: 1.0 },
      { indicator: 'cannabis', year2021: 7.0, year2023: 7.5 },
      { indicator: 'synthetic', year2021: 8.5, year2023: 9.0 },
      { indicator: 'cyber', year2021: 3.5, year2023: 4.0 },
      { indicator: 'financial', year2021: 7.0, year2023: 7.5 },
    ],
  },
  // Add more countries' trend data...
];
