// Crime trends data extracted from Global Organized Crime Index 2023 PDF
// This shows the change in scores from 2021 to 2023

export interface CrimeTrendData {
  countryName: string
  countryCode: string
  category: 'overall' | 'markets' | 'actors' | 'resilience'
  indicator: string
  change: number // The change value shown in the PDF (e.g., +0.56)
  previousScore?: number // If we can calculate it
  currentScore?: number // If we have it
}

// Overall criminality score changes (from page 1 of the PDF)
export const criminalityTrends: CrimeTrendData[] = [
  { countryName: 'Myanmar', countryCode: 'MM', category: 'overall', indicator: 'Criminality Score', change: 0.56 },
  { countryName: 'Colombia', countryCode: 'CO', category: 'overall', indicator: 'Criminality Score', change: 0.09 },
  { countryName: 'Mexico', countryCode: 'MX', category: 'overall', indicator: 'Criminality Score', change: 0.01 },
  { countryName: 'Paraguay', countryCode: 'PY', category: 'overall', indicator: 'Criminality Score', change: 0.82 },
  { countryName: 'Congo, Dem. Rep', countryCode: 'CD', category: 'overall', indicator: 'Criminality Score', change: -0.40 },
  { countryName: 'Nigeria', countryCode: 'NG', category: 'overall', indicator: 'Criminality Score', change: 0.13 },
  { countryName: 'South Africa', countryCode: 'ZA', category: 'overall', indicator: 'Criminality Score', change: 0.56 },
  { countryName: 'Iraq', countryCode: 'IQ', category: 'overall', indicator: 'Criminality Score', change: 0.08 },
  { countryName: 'Afghanistan', countryCode: 'AF', category: 'overall', indicator: 'Criminality Score', change: 0.02 },
  { countryName: 'Lebanon', countryCode: 'LB', category: 'overall', indicator: 'Criminality Score', change: 0.34 },
  { countryName: 'Ecuador', countryCode: 'EC', category: 'overall', indicator: 'Criminality Score', change: 0.82 },
  { countryName: 'Syria', countryCode: 'SY', category: 'overall', indicator: 'Criminality Score', change: 0.23 },
  { countryName: 'Honduras', countryCode: 'HN', category: 'overall', indicator: 'Criminality Score', change: 0.08 },
  { countryName: 'Iran', countryCode: 'IR', category: 'overall', indicator: 'Criminality Score', change: -0.07 },
  { countryName: 'Turkey', countryCode: 'TR', category: 'overall', indicator: 'Criminality Score', change: 0.14 },
  { countryName: 'Kenya', countryCode: 'KE', category: 'overall', indicator: 'Criminality Score', change: 0.07 },
  { countryName: 'Panama', countryCode: 'PA', category: 'overall', indicator: 'Criminality Score', change: 0.31 },
  { countryName: 'Libya', countryCode: 'LY', category: 'overall', indicator: 'Criminality Score', change: 0.38 },
  { countryName: 'Russia', countryCode: 'RU', category: 'overall', indicator: 'Criminality Score', change: 0.63 },
  { countryName: 'Cambodia', countryCode: 'KH', category: 'overall', indicator: 'Criminality Score', change: 1.03 },
  { countryName: 'Indonesia', countryCode: 'ID', category: 'overall', indicator: 'Criminality Score', change: 0.48 },
  { countryName: 'Brazil', countryCode: 'BR', category: 'overall', indicator: 'Criminality Score', change: 0.27 },
  { countryName: 'Central African Republic', countryCode: 'CF', category: 'overall', indicator: 'Criminality Score', change: -0.29 },
  { countryName: 'Venezuela', countryCode: 'VE', category: 'overall', indicator: 'Criminality Score', change: 0.08 },
  { countryName: 'Philippines', countryCode: 'PH', category: 'overall', indicator: 'Criminality Score', change: -0.21 },
  { countryName: 'Guatemala', countryCode: 'GT', category: 'overall', indicator: 'Criminality Score', change: 0.13 },
  { countryName: 'Nepal', countryCode: 'NP', category: 'overall', indicator: 'Criminality Score', change: 0.41 },
  { countryName: 'Yemen', countryCode: 'YE', category: 'overall', indicator: 'Criminality Score', change: 0.45 },
  { countryName: 'Uganda', countryCode: 'UG', category: 'overall', indicator: 'Criminality Score', change: 0.41 },
  { countryName: 'Vietnam', countryCode: 'VN', category: 'overall', indicator: 'Criminality Score', change: 0.27 },
  { countryName: 'Ukraine', countryCode: 'UA', category: 'overall', indicator: 'Criminality Score', change: 0.31 },
  { countryName: 'Peru', countryCode: 'PE', category: 'overall', indicator: 'Criminality Score', change: 0.05 },
  { countryName: 'China', countryCode: 'CN', category: 'overall', indicator: 'Criminality Score', change: 0.36 },
  { countryName: 'Sudan', countryCode: 'SD', category: 'overall', indicator: 'Criminality Score', change: -0.09 },
  { countryName: 'United Arab Emirates', countryCode: 'AE', category: 'overall', indicator: 'Criminality Score', change: 0.62 },
  { countryName: 'South Sudan', countryCode: 'SS', category: 'overall', indicator: 'Criminality Score', change: -0.02 },
  { countryName: 'Cameroon', countryCode: 'CM', category: 'overall', indicator: 'Criminality Score', change: -0.04 },
  { countryName: 'Malaysia', countryCode: 'MY', category: 'overall', indicator: 'Criminality Score', change: 0.29 },
  { countryName: 'Saudi Arabia', countryCode: 'SA', category: 'overall', indicator: 'Criminality Score', change: 0.22 },
  { countryName: 'Italy', countryCode: 'IT', category: 'overall', indicator: 'Criminality Score', change: 0.41 },
  { countryName: 'Serbia', countryCode: 'RS', category: 'overall', indicator: 'Criminality Score', change: 0.01 },
  { countryName: 'Mozambique', countryCode: 'MZ', category: 'overall', indicator: 'Criminality Score', change: -0.33 },
  { countryName: 'Tanzania', countryCode: 'TZ', category: 'overall', indicator: 'Criminality Score', change: 0.05 },
  { countryName: 'Thailand', countryCode: 'TH', category: 'overall', indicator: 'Criminality Score', change: 0.42 },
  { countryName: 'Somalia', countryCode: 'SO', category: 'overall', indicator: 'Criminality Score', change: 0.34 },
  { countryName: 'Laos', countryCode: 'LA', category: 'overall', indicator: 'Criminality Score', change: 0.61 },
  { countryName: 'Pakistan', countryCode: 'PK', category: 'overall', indicator: 'Criminality Score', change: -0.25 },
  { countryName: "Côte d'Ivoire", countryCode: 'CI', category: 'overall', indicator: 'Criminality Score', change: -0.13 },
  { countryName: 'Guyana', countryCode: 'GY', category: 'overall', indicator: 'Criminality Score', change: 0.87 },
  { countryName: 'Haiti', countryCode: 'HT', category: 'overall', indicator: 'Criminality Score', change: 0.21 },
  { countryName: 'Mali', countryCode: 'ML', category: 'overall', indicator: 'Criminality Score', change: 0.04 },
  { countryName: 'Burkina Faso', countryCode: 'BF', category: 'overall', indicator: 'Criminality Score', change: 0.43 },
  { countryName: 'El Salvador', countryCode: 'SV', category: 'overall', indicator: 'Criminality Score', change: -0.02 },
  { countryName: 'Montenegro', countryCode: 'ME', category: 'overall', indicator: 'Criminality Score', change: -0.10 },
  { countryName: 'Spain', countryCode: 'ES', category: 'overall', indicator: 'Criminality Score', change: 0.13 },
  { countryName: 'Belarus', countryCode: 'BY', category: 'overall', indicator: 'Criminality Score', change: 0.80 },
  { countryName: 'Bosnia and Herzegovina', countryCode: 'BA', category: 'overall', indicator: 'Criminality Score', change: -0.04 },
  { countryName: 'France', countryCode: 'FR', category: 'overall', indicator: 'Criminality Score', change: 0.16 },
  { countryName: 'Ghana', countryCode: 'GH', category: 'overall', indicator: 'Criminality Score', change: -0.21 },
  { countryName: 'Jamaica', countryCode: 'JM', category: 'overall', indicator: 'Criminality Score', change: -0.11 },
  { countryName: 'India', countryCode: 'IN', category: 'overall', indicator: 'Criminality Score', change: 0.23 },
  { countryName: 'United Kingdom', countryCode: 'GB', category: 'overall', indicator: 'Criminality Score', change: 0.86 },
  { countryName: 'Nicaragua', countryCode: 'NI', category: 'overall', indicator: 'Criminality Score', change: -0.34 },
  { countryName: 'Papua New Guinea', countryCode: 'PG', category: 'overall', indicator: 'Criminality Score', change: 0.28 },
  { countryName: 'Niger', countryCode: 'NE', category: 'overall', indicator: 'Criminality Score', change: -0.31 },
  { countryName: 'Ethiopia', countryCode: 'ET', category: 'overall', indicator: 'Criminality Score', change: 0.89 },
  { countryName: 'United States', countryCode: 'US', category: 'overall', indicator: 'Criminality Score', change: 0.17 },
  { countryName: 'Bulgaria', countryCode: 'BG', category: 'overall', indicator: 'Criminality Score', change: 0.23 },
  { countryName: 'Moldova', countryCode: 'MD', category: 'overall', indicator: 'Criminality Score', change: 1.15 },
  { countryName: 'Angola', countryCode: 'AO', category: 'overall', indicator: 'Criminality Score', change: 0.29 },
  { countryName: 'Madagascar', countryCode: 'MG', category: 'overall', indicator: 'Criminality Score', change: -0.01 },
  { countryName: 'Costa Rica', countryCode: 'CR', category: 'overall', indicator: 'Criminality Score', change: 0.54 },
  { countryName: 'Senegal', countryCode: 'SN', category: 'overall', indicator: 'Criminality Score', change: 0.71 },
  { countryName: 'Chad', countryCode: 'TD', category: 'overall', indicator: 'Criminality Score', change: -0.36 },
  { countryName: 'Liberia', countryCode: 'LR', category: 'overall', indicator: 'Criminality Score', change: 0.45 },
  { countryName: 'Zimbabwe', countryCode: 'ZW', category: 'overall', indicator: 'Criminality Score', change: -0.19 },
  { countryName: 'Qatar', countryCode: 'QA', category: 'overall', indicator: 'Criminality Score', change: 0.24 },
  { countryName: 'Tajikistan', countryCode: 'TJ', category: 'overall', indicator: 'Criminality Score', change: -0.16 },
  { countryName: 'Greece', countryCode: 'GR', category: 'overall', indicator: 'Criminality Score', change: 0.43 },
  { countryName: 'Germany', countryCode: 'DE', category: 'overall', indicator: 'Criminality Score', change: 0.43 },
  { countryName: 'Benin', countryCode: 'BJ', category: 'overall', indicator: 'Criminality Score', change: 0.07 },
  { countryName: 'Kyrgyzstan', countryCode: 'KG', category: 'overall', indicator: 'Criminality Score', change: 0.00 },
  { countryName: 'Togo', countryCode: 'TG', category: 'overall', indicator: 'Criminality Score', change: -0.09 },
  { countryName: 'Kuwait', countryCode: 'KW', category: 'overall', indicator: 'Criminality Score', change: 0.06 },
  { countryName: 'Trinidad and Tobago', countryCode: 'TT', category: 'overall', indicator: 'Criminality Score', change: 0.26 },
  { countryName: 'Chile', countryCode: 'CL', category: 'overall', indicator: 'Criminality Score', change: 0.58 },
  { countryName: 'Albania', countryCode: 'AL', category: 'overall', indicator: 'Criminality Score', change: -0.46 },
  { countryName: 'Croatia', countryCode: 'HR', category: 'overall', indicator: 'Criminality Score', change: 0.09 },
  { countryName: 'Bangladesh', countryCode: 'BD', category: 'overall', indicator: 'Criminality Score', change: 0.15 },
  { countryName: 'Guinea-Bissau', countryCode: 'GW', category: 'overall', indicator: 'Criminality Score', change: -0.35 },
  { countryName: 'Ireland', countryCode: 'IE', category: 'overall', indicator: 'Criminality Score', change: 0.18 },
  { countryName: 'Egypt', countryCode: 'EG', category: 'overall', indicator: 'Criminality Score', change: -0.11 },
  { countryName: 'North Macedonia', countryCode: 'MK', category: 'overall', indicator: 'Criminality Score', change: -0.28 },
  { countryName: 'Dominican Republic', countryCode: 'DO', category: 'overall', indicator: 'Criminality Score', change: -0.13 },
  { countryName: 'Argentina', countryCode: 'AR', category: 'overall', indicator: 'Criminality Score', change: 0.63 },
  { countryName: 'Malta', countryCode: 'MT', category: 'overall', indicator: 'Criminality Score', change: 0.35 },
  { countryName: 'Kosovo', countryCode: 'XK', category: 'overall', indicator: 'Criminality Score', change: -0.22 },
  { countryName: 'Netherlands', countryCode: 'NL', category: 'overall', indicator: 'Criminality Score', change: 0.28 },
  { countryName: 'Bahrain', countryCode: 'BH', category: 'overall', indicator: 'Criminality Score', change: 0.13 },
  { countryName: 'Bolivia', countryCode: 'BO', category: 'overall', indicator: 'Criminality Score', change: 0.65 },
  { countryName: 'Sierra Leone', countryCode: 'SL', category: 'overall', indicator: 'Criminality Score', change: -0.45 },
  { countryName: 'Uzbekistan', countryCode: 'UZ', category: 'overall', indicator: 'Criminality Score', change: -0.01 },
  { countryName: 'Jordan', countryCode: 'JO', category: 'overall', indicator: 'Criminality Score', change: 0.22 },
  { countryName: 'Sri Lanka', countryCode: 'LK', category: 'overall', indicator: 'Criminality Score', change: 0.28 },
  { countryName: 'Algeria', countryCode: 'DZ', category: 'overall', indicator: 'Criminality Score', change: 0.37 },
  { countryName: 'Portugal', countryCode: 'PT', category: 'overall', indicator: 'Criminality Score', change: 0.33 },
  { countryName: 'Belize', countryCode: 'BZ', category: 'overall', indicator: 'Criminality Score', change: 0.23 },
  { countryName: 'Burundi', countryCode: 'BI', category: 'overall', indicator: 'Criminality Score', change: 0.36 },
  { countryName: 'Switzerland', countryCode: 'CH', category: 'overall', indicator: 'Criminality Score', change: 0.53 },
  { countryName: 'Gabon', countryCode: 'GA', category: 'overall', indicator: 'Criminality Score', change: -0.05 },
  { countryName: 'Israel', countryCode: 'IL', category: 'overall', indicator: 'Criminality Score', change: 0.44 },
  { countryName: 'Korea, DPR', countryCode: 'KP', category: 'overall', indicator: 'Criminality Score', change: 0.04 },
  { countryName: 'Azerbaijan', countryCode: 'AZ', category: 'overall', indicator: 'Criminality Score', change: -0.28 },
  { countryName: 'Morocco', countryCode: 'MA', category: 'overall', indicator: 'Criminality Score', change: 0.01 },
  { countryName: 'Congo, Rep', countryCode: 'CG', category: 'overall', indicator: 'Criminality Score', change: -0.25 },
  { countryName: 'Suriname', countryCode: 'SR', category: 'overall', indicator: 'Criminality Score', change: -0.13 },
  { countryName: 'Zambia', countryCode: 'ZM', category: 'overall', indicator: 'Criminality Score', change: -0.19 },
  { countryName: 'Slovakia', countryCode: 'SK', category: 'overall', indicator: 'Criminality Score', change: 0.03 },
  { countryName: 'Sweden', countryCode: 'SE', category: 'overall', indicator: 'Criminality Score', change: 0.14 },
  { countryName: 'Czech Republic', countryCode: 'CZ', category: 'overall', indicator: 'Criminality Score', change: 0.05 },
  { countryName: 'Djibouti', countryCode: 'DJ', category: 'overall', indicator: 'Criminality Score', change: 0.66 },
  { countryName: 'Hungary', countryCode: 'HU', category: 'overall', indicator: 'Criminality Score', change: 0.12 },
  { countryName: 'Guinea', countryCode: 'GN', category: 'overall', indicator: 'Criminality Score', change: -0.62 },
  { countryName: 'Romania', countryCode: 'RO', category: 'overall', indicator: 'Criminality Score', change: -0.01 },
  { countryName: 'Gambia', countryCode: 'GM', category: 'overall', indicator: 'Criminality Score', change: -0.30 },
  { countryName: 'Malawi', countryCode: 'MW', category: 'overall', indicator: 'Criminality Score', change: 0.66 },
  { countryName: 'Poland', countryCode: 'PL', category: 'overall', indicator: 'Criminality Score', change: 0.47 },
  { countryName: 'Kazakhstan', countryCode: 'KZ', category: 'overall', indicator: 'Criminality Score', change: 0.21 },
  { countryName: 'Tunisia', countryCode: 'TN', category: 'overall', indicator: 'Criminality Score', change: 0.66 },
  { countryName: 'Belgium', countryCode: 'BE', category: 'overall', indicator: 'Criminality Score', change: 0.09 },
  { countryName: 'Cyprus', countryCode: 'CY', category: 'overall', indicator: 'Criminality Score', change: 0.24 },
  { countryName: 'Korea, Rep.', countryCode: 'KR', category: 'overall', indicator: 'Criminality Score', change: -0.48 },
  { countryName: 'Oman', countryCode: 'OM', category: 'overall', indicator: 'Criminality Score', change: 0.26 },
  { countryName: 'Solomon Islands', countryCode: 'SB', category: 'overall', indicator: 'Criminality Score', change: 0.25 },
  { countryName: 'Turkmenistan', countryCode: 'TM', category: 'overall', indicator: 'Criminality Score', change: -0.21 },
  { countryName: 'Equatorial Guinea', countryCode: 'GQ', category: 'overall', indicator: 'Criminality Score', change: 0.27 },
  { countryName: 'Eswatini', countryCode: 'SZ', category: 'overall', indicator: 'Criminality Score', change: 0.76 },
  { countryName: 'Mauritania', countryCode: 'MR', category: 'overall', indicator: 'Criminality Score', change: 0.00 },
  { countryName: 'Mauritius', countryCode: 'MU', category: 'overall', indicator: 'Criminality Score', change: -0.14 },
  { countryName: 'Slovenia', countryCode: 'SI', category: 'overall', indicator: 'Criminality Score', change: 0.08 },
  { countryName: 'Botswana', countryCode: 'BW', category: 'overall', indicator: 'Criminality Score', change: 0.64 },
  { countryName: 'Namibia', countryCode: 'NA', category: 'overall', indicator: 'Criminality Score', change: -0.03 },
  { countryName: 'Cabo Verde', countryCode: 'CV', category: 'overall', indicator: 'Criminality Score', change: 0.24 },
  { countryName: 'Japan', countryCode: 'JP', category: 'overall', indicator: 'Criminality Score', change: -0.25 },
  { countryName: 'Maldives', countryCode: 'MV', category: 'overall', indicator: 'Criminality Score', change: 0.21 },
  { countryName: 'Estonia', countryCode: 'EE', category: 'overall', indicator: 'Criminality Score', change: 0.65 },
  { countryName: 'Fiji', countryCode: 'FJ', category: 'overall', indicator: 'Criminality Score', change: 0.25 },
  { countryName: 'Austria', countryCode: 'AT', category: 'overall', indicator: 'Criminality Score', change: 0.09 },
  { countryName: 'Mongolia', countryCode: 'MN', category: 'overall', indicator: 'Criminality Score', change: 0.11 },
  { countryName: 'New Zealand', countryCode: 'NZ', category: 'overall', indicator: 'Criminality Score', change: 0.83 },
  { countryName: 'Timor-Leste', countryCode: 'TL', category: 'overall', indicator: 'Criminality Score', change: 0.12 },
  { countryName: 'Denmark', countryCode: 'DK', category: 'overall', indicator: 'Criminality Score', change: 0.16 },
  { countryName: 'Australia', countryCode: 'AU', category: 'overall', indicator: 'Criminality Score', change: 0.00 },
  { countryName: 'Eritrea', countryCode: 'ER', category: 'overall', indicator: 'Criminality Score', change: -0.37 },
  { countryName: 'Comoros', countryCode: 'KM', category: 'overall', indicator: 'Criminality Score', change: 0.06 },
  { countryName: 'Lesotho', countryCode: 'LS', category: 'overall', indicator: 'Criminality Score', change: 0.02 },
  { countryName: 'Bhutan', countryCode: 'BT', category: 'overall', indicator: 'Criminality Score', change: 0.21 },
  { countryName: 'Latvia', countryCode: 'LV', category: 'overall', indicator: 'Criminality Score', change: 0.39 },
  { countryName: 'Lithuania', countryCode: 'LT', category: 'overall', indicator: 'Criminality Score', change: 0.59 },
  { countryName: 'Seychelles', countryCode: 'SC', category: 'overall', indicator: 'Criminality Score', change: 0.23 },
  { countryName: 'Canada', countryCode: 'CA', category: 'overall', indicator: 'Criminality Score', change: 0.22 },
  { countryName: 'Bahamas', countryCode: 'BS', category: 'overall', indicator: 'Criminality Score', change: -0.04 },
  { countryName: 'Norway', countryCode: 'NO', category: 'overall', indicator: 'Criminality Score', change: -0.06 },
  { countryName: 'Tonga', countryCode: 'TO', category: 'overall', indicator: 'Criminality Score', change: -0.07 },
  { countryName: 'Georgia', countryCode: 'GE', category: 'overall', indicator: 'Criminality Score', change: 0.64 },
  { countryName: 'Rwanda', countryCode: 'RW', category: 'overall', indicator: 'Criminality Score', change: -0.07 },
  { countryName: 'St. Lucia', countryCode: 'LC', category: 'overall', indicator: 'Criminality Score', change: -0.56 },
  { countryName: 'St. Kitts and Nevis', countryCode: 'KN', category: 'overall', indicator: 'Criminality Score', change: -0.58 },
  { countryName: 'San Marino', countryCode: 'SM', category: 'overall', indicator: 'Criminality Score', change: 0.47 },
  { countryName: 'Singapore', countryCode: 'SG', category: 'overall', indicator: 'Criminality Score', change: 0.35 },
  { countryName: 'Cuba', countryCode: 'CU', category: 'overall', indicator: 'Criminality Score', change: -0.07 },
  { countryName: 'Iceland', countryCode: 'IS', category: 'overall', indicator: 'Criminality Score', change: -0.02 },
  { countryName: 'Andorra', countryCode: 'AD', category: 'overall', indicator: 'Criminality Score', change: 0.26 },
  { countryName: 'Uruguay', countryCode: 'UY', category: 'overall', indicator: 'Criminality Score', change: 0.53 },
  { countryName: 'St. Vincent and the Grenadines', countryCode: 'VC', category: 'overall', indicator: 'Criminality Score', change: -0.22 },
  { countryName: 'Barbados', countryCode: 'BB', category: 'overall', indicator: 'Criminality Score', change: -0.14 },
  { countryName: 'Micronesia (Federated States of)', countryCode: 'FM', category: 'overall', indicator: 'Criminality Score', change: -0.30 },
  { countryName: 'Antigua and Barbuda', countryCode: 'AG', category: 'overall', indicator: 'Criminality Score', change: -0.36 },
  { countryName: 'Finland', countryCode: 'FI', category: 'overall', indicator: 'Criminality Score', change: 0.27 },
  { countryName: 'Grenada', countryCode: 'GD', category: 'overall', indicator: 'Criminality Score', change: -0.12 },
  { countryName: 'Brunei', countryCode: 'BN', category: 'overall', indicator: 'Criminality Score', change: 0.09 },
  { countryName: 'Luxembourg', countryCode: 'LU', category: 'overall', indicator: 'Criminality Score', change: 0.49 },
  { countryName: 'Armenia', countryCode: 'AM', category: 'overall', indicator: 'Criminality Score', change: -0.44 },
  { countryName: 'Palau', countryCode: 'PW', category: 'overall', indicator: 'Criminality Score', change: -0.24 },
  { countryName: 'Dominica', countryCode: 'DM', category: 'overall', indicator: 'Criminality Score', change: 0.00 },
  { countryName: 'Monaco', countryCode: 'MC', category: 'overall', indicator: 'Criminality Score', change: 0.16 },
  { countryName: 'Marshall Islands', countryCode: 'MH', category: 'overall', indicator: 'Criminality Score', change: 0.21 },
  { countryName: 'Kiribati', countryCode: 'KI', category: 'overall', indicator: 'Criminality Score', change: 0.10 },
  { countryName: 'Samoa', countryCode: 'WS', category: 'overall', indicator: 'Criminality Score', change: 0.39 },
  { countryName: 'Vanuatu', countryCode: 'VU', category: 'overall', indicator: 'Criminality Score', change: 0.23 },
  { countryName: 'Liechtenstein', countryCode: 'LI', category: 'overall', indicator: 'Criminality Score', change: 0.40 },
  { countryName: 'Nauru', countryCode: 'NR', category: 'overall', indicator: 'Criminality Score', change: 0.29 },
  { countryName: 'São Tomé and Príncipe', countryCode: 'ST', category: 'overall', indicator: 'Criminality Score', change: -0.08 },
  { countryName: 'Tuvalu', countryCode: 'TV', category: 'overall', indicator: 'Criminality Score', change: 0.08 },
]

// Criminal Markets trends (sample from the PDF - you can add more specific indicators)
export const criminalMarketsTrends: CrimeTrendData[] = [
  // Mexico criminal markets
  { countryName: 'Mexico', countryCode: 'MX', category: 'markets', indicator: 'Overall Criminal Markets', change: 0.13 },
  { countryName: 'Mexico', countryCode: 'MX', category: 'markets', indicator: 'Human Trafficking', change: 0.5 },
  { countryName: 'Mexico', countryCode: 'MX', category: 'markets', indicator: 'Human Smuggling', change: 0.5 },
  { countryName: 'Mexico', countryCode: 'MX', category: 'markets', indicator: 'Arms Trafficking', change: 0.5 },
  
  // Myanmar criminal markets
  { countryName: 'Myanmar', countryCode: 'MM', category: 'markets', indicator: 'Overall Criminal Markets', change: 0.65 },
  { countryName: 'Myanmar', countryCode: 'MM', category: 'markets', indicator: 'Human Trafficking', change: 2.0 },
  { countryName: 'Myanmar', countryCode: 'MM', category: 'markets', indicator: 'Human Smuggling', change: 0.5 },
  { countryName: 'Myanmar', countryCode: 'MM', category: 'markets', indicator: 'Arms Trafficking', change: 1.0 },
  { countryName: 'Myanmar', countryCode: 'MM', category: 'markets', indicator: 'Flora Crimes', change: 1.5 },
  { countryName: 'Myanmar', countryCode: 'MM', category: 'markets', indicator: 'Fauna Crimes', change: 0.5 },
  { countryName: 'Myanmar', countryCode: 'MM', category: 'markets', indicator: 'Non-Renewable Resource Crimes', change: 2.5 },
  { countryName: 'Myanmar', countryCode: 'MM', category: 'markets', indicator: 'Synthetic Drug Trade', change: 0.5 },
  
  // Add more countries as needed...
]

// Criminal Actors trends (sample from the PDF)
export const criminalActorsTrends: CrimeTrendData[] = [
  // Myanmar criminal actors
  { countryName: 'Myanmar', countryCode: 'MM', category: 'actors', indicator: 'Overall Criminal Actors', change: 0.47 },
  { countryName: 'Myanmar', countryCode: 'MM', category: 'actors', indicator: 'Mafia-Style Groups', change: 0.5 },
  { countryName: 'Myanmar', countryCode: 'MM', category: 'actors', indicator: 'Criminal Networks', change: 0.5 },
  { countryName: 'Myanmar', countryCode: 'MM', category: 'actors', indicator: 'State-Embedded Actors', change: 0.5 },
  { countryName: 'Myanmar', countryCode: 'MM', category: 'actors', indicator: 'Foreign Actors', change: 1.5 },
  
  // Congo, Dem. Rep criminal actors
  { countryName: 'Congo, Dem. Rep', countryCode: 'CD', category: 'actors', indicator: 'Overall Criminal Actors', change: -0.50 },
  { countryName: 'Congo, Dem. Rep', countryCode: 'CD', category: 'actors', indicator: 'Mafia-Style Groups', change: 0.0 },
  { countryName: 'Congo, Dem. Rep', countryCode: 'CD', category: 'actors', indicator: 'Criminal Networks', change: 0.0 },
  { countryName: 'Congo, Dem. Rep', countryCode: 'CD', category: 'actors', indicator: 'State-Embedded Actors', change: 0.0 },
  { countryName: 'Congo, Dem. Rep', countryCode: 'CD', category: 'actors', indicator: 'Foreign Actors', change: 0.0 },
  
  // Add more countries as needed...
]

// Resilience trends (sample from the PDF)
export const resilienceTrends: CrimeTrendData[] = [
  // Finland resilience
  { countryName: 'Finland', countryCode: 'FI', category: 'resilience', indicator: 'Overall Resilience', change: 0.21 },
  { countryName: 'Finland', countryCode: 'FI', category: 'resilience', indicator: 'Political Leadership and Governance', change: 0.0 },
  { countryName: 'Finland', countryCode: 'FI', category: 'resilience', indicator: 'Government Transparency', change: 0.5 },
  { countryName: 'Finland', countryCode: 'FI', category: 'resilience', indicator: 'International Cooperation', change: 0.0 },
  { countryName: 'Finland', countryCode: 'FI', category: 'resilience', indicator: 'National Policies and Laws', change: 0.5 },
  { countryName: 'Finland', countryCode: 'FI', category: 'resilience', indicator: 'Law Enforcement', change: 0.5 },
  { countryName: 'Finland', countryCode: 'FI', category: 'resilience', indicator: 'Prevention', change: 0.5 },
  { countryName: 'Finland', countryCode: 'FI', category: 'resilience', indicator: 'Non-State Actors', change: 0.5 },
  
  // Liechtenstein resilience
  { countryName: 'Liechtenstein', countryCode: 'LI', category: 'resilience', indicator: 'Overall Resilience', change: 0.04 },
  { countryName: 'Liechtenstein', countryCode: 'LI', category: 'resilience', indicator: 'Political Leadership and Governance', change: 0.0 },
  { countryName: 'Liechtenstein', countryCode: 'LI', category: 'resilience', indicator: 'Government Transparency', change: 0.0 },
  { countryName: 'Liechtenstein', countryCode: 'LI', category: 'resilience', indicator: 'International Cooperation', change: 0.0 },
  { countryName: 'Liechtenstein', countryCode: 'LI', category: 'resilience', indicator: 'National Policies and Laws', change: 0.0 },
  { countryName: 'Liechtenstein', countryCode: 'LI', category: 'resilience', indicator: 'Law Enforcement', change: 0.5 },
  
  // Add more countries as needed...
]

// Combine all trends
export const allCrimeTrends: CrimeTrendData[] = [
  ...criminalityTrends,
  ...criminalMarketsTrends,
  ...criminalActorsTrends,
  ...resilienceTrends,
]
