// Complete crime index data extracted from Global Organized Crime Index 2023 PDF
// Source: https://ocindex.net/assets/downloads/2023/english/global-ocindex-report.pdf
// Data extracted from pages 209-237

export const crimeIndexData = [
  // Data extracted from the ranking tables in the PDF
  
  // TOP CRIMINALITY SCORES (from page 209-211)
  {
    countryCode: 'MM',
    countryName: 'Myanmar',
    year: 2023,
    criminalityScore: 8.15,
    rank: 1,
    region: 'asia',
  },
  {
    countryCode: 'CO',
    countryName: 'Colombia',
    year: 2023,
    criminalityScore: 7.75,
    rank: 2,
    region: 'americas',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    year: 2023,
    criminalityScore: 7.57,
    rank: 3,
    region: 'americas',
  },
  {
    countryCode: 'PY',
    countryName: 'Paraguay',
    year: 2023,
    criminalityScore: 7.52,
    rank: 4,
    region: 'americas',
  },
  {
    countryCode: 'CD',
    countryName: 'Congo, Dem. Rep',
    year: 2023,
    criminalityScore: 7.35,
    rank: 5,
    region: 'africa',
  },
  {
    countryCode: 'NG',
    countryName: 'Nigeria',
    year: 2023,
    criminalityScore: 7.28,
    rank: 6,
    region: 'africa',
  },
  {
    countryCode: 'ZA',
    countryName: 'South Africa',
    year: 2023,
    criminalityScore: 7.18,
    rank: 7,
    region: 'africa',
  },
  {
    countryCode: 'IQ',
    countryName: 'Iraq',
    year: 2023,
    criminalityScore: 7.13,
    rank: 8,
    region: 'asia',
  },
  {
    countryCode: 'AF',
    countryName: 'Afghanistan',
    year: 2023,
    criminalityScore: 7.10,
    rank: 9,
    region: 'asia',
  },
  {
    countryCode: 'LB',
    countryName: 'Lebanon',
    year: 2023,
    criminalityScore: 7.10,
    rank: 9,
    region: 'asia',
  },
  {
    countryCode: 'EC',
    countryName: 'Ecuador',
    year: 2023,
    criminalityScore: 7.07,
    rank: 11,
    region: 'americas',
  },
  {
    countryCode: 'SY',
    countryName: 'Syria',
    year: 2023,
    criminalityScore: 7.07,
    rank: 11,
    region: 'asia',
  },
  {
    countryCode: 'HN',
    countryName: 'Honduras',
    year: 2023,
    criminalityScore: 7.05,
    rank: 13,
    region: 'americas',
  },
  {
    countryCode: 'IR',
    countryName: 'Iran',
    year: 2023,
    criminalityScore: 7.03,
    rank: 14,
    region: 'asia',
  },
  {
    countryCode: 'TR',
    countryName: 'Turkey',
    year: 2023,
    criminalityScore: 7.03,
    rank: 14,
    region: 'asia',
  },
  {
    countryCode: 'KE',
    countryName: 'Kenya',
    year: 2023,
    criminalityScore: 7.02,
    rank: 16,
    region: 'africa',
  },
  {
    countryCode: 'PA',
    countryName: 'Panama',
    year: 2023,
    criminalityScore: 6.98,
    rank: 17,
    region: 'americas',
  },
  {
    countryCode: 'LY',
    countryName: 'Libya',
    year: 2023,
    criminalityScore: 6.93,
    rank: 18,
    region: 'africa',
  },
  {
    countryCode: 'RU',
    countryName: 'Russia',
    year: 2023,
    criminalityScore: 6.87,
    rank: 19,
    region: 'europe',
  },
  {
    countryCode: 'KH',
    countryName: 'Cambodia',
    year: 2023,
    criminalityScore: 6.85,
    rank: 20,
    region: 'asia',
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    year: 2023,
    criminalityScore: 6.85,
    rank: 20,
    region: 'asia',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    year: 2023,
    criminalityScore: 6.77,
    rank: 22,
    region: 'americas',
  },
  {
    countryCode: 'CF',
    countryName: 'Central African Republic',
    year: 2023,
    criminalityScore: 6.75,
    rank: 23,
    region: 'africa',
  },
  {
    countryCode: 'VE',
    countryName: 'Venezuela',
    year: 2023,
    criminalityScore: 6.72,
    rank: 24,
    region: 'americas',
  },
  {
    countryCode: 'PH',
    countryName: 'Philippines',
    year: 2023,
    criminalityScore: 6.63,
    rank: 25,
    region: 'asia',
  },
  {
    countryCode: 'GT',
    countryName: 'Guatemala',
    year: 2023,
    criminalityScore: 6.60,
    rank: 26,
    region: 'americas',
  },
  {
    countryCode: 'NP',
    countryName: 'Nepal',
    year: 2023,
    criminalityScore: 6.57,
    rank: 27,
    region: 'asia',
  },
  {
    countryCode: 'YE',
    countryName: 'Yemen',
    year: 2023,
    criminalityScore: 6.57,
    rank: 27,
    region: 'asia',
  },
  {
    countryCode: 'UG',
    countryName: 'Uganda',
    year: 2023,
    criminalityScore: 6.55,
    rank: 29,
    region: 'africa',
  },
  {
    countryCode: 'VN',
    countryName: 'Vietnam',
    year: 2023,
    criminalityScore: 6.55,
    rank: 29,
    region: 'asia',
  },
  {
    countryCode: 'UA',
    countryName: 'Ukraine',
    year: 2023,
    criminalityScore: 6.48,
    rank: 31,
    region: 'europe',
  },
  {
    countryCode: 'PE',
    countryName: 'Peru',
    year: 2023,
    criminalityScore: 6.40,
    rank: 32,
    region: 'americas',
  },
  {
    countryCode: 'CN',
    countryName: 'China',
    year: 2023,
    criminalityScore: 6.37,
    rank: 33,
    region: 'asia',
  },
  {
    countryCode: 'SD',
    countryName: 'Sudan',
    year: 2023,
    criminalityScore: 6.37,
    rank: 33,
    region: 'africa',
  },
  {
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    year: 2023,
    criminalityScore: 6.37,
    rank: 33,
    region: 'asia',
  },
  {
    countryCode: 'SS',
    countryName: 'South Sudan',
    year: 2023,
    criminalityScore: 6.32,
    rank: 36,
    region: 'africa',
  },
  {
    countryCode: 'CM',
    countryName: 'Cameroon',
    year: 2023,
    criminalityScore: 6.27,
    rank: 37,
    region: 'africa',
  },
  {
    countryCode: 'MY',
    countryName: 'Malaysia',
    year: 2023,
    criminalityScore: 6.23,
    rank: 38,
    region: 'asia',
  },
  {
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    year: 2023,
    criminalityScore: 6.23,
    rank: 38,
    region: 'asia',
  },
  {
    countryCode: 'IT',
    countryName: 'Italy',
    year: 2023,
    criminalityScore: 6.22,
    rank: 40,
    region: 'europe',
  },
  {
    countryCode: 'RS',
    countryName: 'Serbia',
    year: 2023,
    criminalityScore: 6.22,
    rank: 40,
    region: 'europe',
  },
  {
    countryCode: 'MZ',
    countryName: 'Mozambique',
    year: 2023,
    criminalityScore: 6.20,
    rank: 42,
    region: 'africa',
  },
  {
    countryCode: 'TZ',
    countryName: 'Tanzania',
    year: 2023,
    criminalityScore: 6.20,
    rank: 42,
    region: 'africa',
  },
  {
    countryCode: 'TH',
    countryName: 'Thailand',
    year: 2023,
    criminalityScore: 6.18,
    rank: 44,
    region: 'asia',
  },
  {
    countryCode: 'SO',
    countryName: 'Somalia',
    year: 2023,
    criminalityScore: 6.13,
    rank: 45,
    region: 'africa',
  },
  {
    countryCode: 'LA',
    countryName: 'Laos',
    year: 2023,
    criminalityScore: 6.12,
    rank: 46,
    region: 'asia',
  },
  {
    countryCode: 'PK',
    countryName: 'Pakistan',
    year: 2023,
    criminalityScore: 6.03,
    rank: 47,
    region: 'asia',
  },
  {
    countryCode: 'CI',
    countryName: 'Côte d\'Ivoire',
    year: 2023,
    criminalityScore: 6.02,
    rank: 48,
    region: 'africa',
  },
  {
    countryCode: 'GY',
    countryName: 'Guyana',
    year: 2023,
    criminalityScore: 5.97,
    rank: 49,
    region: 'americas',
  },
  {
    countryCode: 'HT',
    countryName: 'Haiti',
    year: 2023,
    criminalityScore: 5.93,
    rank: 50,
    region: 'americas',
  },
  {
    countryCode: 'ML',
    countryName: 'Mali',
    year: 2023,
    criminalityScore: 5.93,
    rank: 50,
    region: 'africa',
  },
  {
    countryCode: 'BF',
    countryName: 'Burkina Faso',
    year: 2023,
    criminalityScore: 5.92,
    rank: 52,
    region: 'africa',
  },
  {
    countryCode: 'SV',
    countryName: 'El Salvador',
    year: 2023,
    criminalityScore: 5.92,
    rank: 52,
    region: 'americas',
  },
  {
    countryCode: 'ME',
    countryName: 'Montenegro',
    year: 2023,
    criminalityScore: 5.90,
    rank: 54,
    region: 'europe',
  },
  {
    countryCode: 'ES',
    countryName: 'Spain',
    year: 2023,
    criminalityScore: 5.90,
    rank: 54,
    region: 'europe',
  },
  {
    countryCode: 'BY',
    countryName: 'Belarus',
    year: 2023,
    criminalityScore: 5.87,
    rank: 56,
    region: 'europe',
  },
  {
    countryCode: 'BA',
    countryName: 'Bosnia and Herzegovina',
    year: 2023,
    criminalityScore: 5.85,
    rank: 57,
    region: 'europe',
  },
  {
    countryCode: 'FR',
    countryName: 'France',
    year: 2023,
    criminalityScore: 5.82,
    rank: 58,
    region: 'europe',
  },
  {
    countryCode: 'GH',
    countryName: 'Ghana',
    year: 2023,
    criminalityScore: 5.80,
    rank: 59,
    region: 'africa',
  },
  {
    countryCode: 'JM',
    countryName: 'Jamaica',
    year: 2023,
    criminalityScore: 5.80,
    rank: 59,
    region: 'americas',
  },
  {
    countryCode: 'IN',
    countryName: 'India',
    year: 2023,
    criminalityScore: 5.75,
    rank: 61,
    region: 'asia',
  },
  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    year: 2023,
    criminalityScore: 5.75,
    rank: 61,
    region: 'europe',
  },
  {
    countryCode: 'NI',
    countryName: 'Nicaragua',
    year: 2023,
    criminalityScore: 5.72,
    rank: 63,
    region: 'americas',
  },
  {
    countryCode: 'PG',
    countryName: 'Papua New Guinea',
    year: 2023,
    criminalityScore: 5.72,
    rank: 63,
    region: 'oceania',
  },
  {
    countryCode: 'NE',
    countryName: 'Niger',
    year: 2023,
    criminalityScore: 5.70,
    rank: 65,
    region: 'africa',
  },
  {
    countryCode: 'ET',
    countryName: 'Ethiopia',
    year: 2023,
    criminalityScore: 5.68,
    rank: 66,
    region: 'africa',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    year: 2023,
    criminalityScore: 5.67,
    rank: 67,
    region: 'americas',
  },
  {
    countryCode: 'BG',
    countryName: 'Bulgaria',
    year: 2023,
    criminalityScore: 5.65,
    rank: 68,
    region: 'europe',
  },
  {
    countryCode: 'MD',
    countryName: 'Moldova',
    year: 2023,
    criminalityScore: 5.60,
    rank: 69,
    region: 'europe',
  },
  {
    countryCode: 'AO',
    countryName: 'Angola',
    year: 2023,
    criminalityScore: 5.58,
    rank: 70,
    region: 'africa',
  },
  {
    countryCode: 'MG',
    countryName: 'Madagascar',
    year: 2023,
    criminalityScore: 5.58,
    rank: 70,
    region: 'africa',
  },
  {
    countryCode: 'CR',
    countryName: 'Costa Rica',
    year: 2023,
    criminalityScore: 5.53,
    rank: 72,
    region: 'americas',
  },
  {
    countryCode: 'SN',
    countryName: 'Senegal',
    year: 2023,
    criminalityScore: 5.52,
    rank: 73,
    region: 'africa',
  },
  {
    countryCode: 'TD',
    countryName: 'Chad',
    year: 2023,
    criminalityScore: 5.50,
    rank: 74,
    region: 'africa',
  },
  {
    countryCode: 'LR',
    countryName: 'Liberia',
    year: 2023,
    criminalityScore: 5.50,
    rank: 74,
    region: 'africa',
  },
  {
    countryCode: 'ZW',
    countryName: 'Zimbabwe',
    year: 2023,
    criminalityScore: 5.47,
    rank: 76,
    region: 'africa',
  },
  {
    countryCode: 'QA',
    countryName: 'Qatar',
    year: 2023,
    criminalityScore: 5.45,
    rank: 77,
    region: 'asia',
  },
  {
    countryCode: 'TJ',
    countryName: 'Tajikistan',
    year: 2023,
    criminalityScore: 5.45,
    rank: 77,
    region: 'asia',
  },
  {
    countryCode: 'GR',
    countryName: 'Greece',
    year: 2023,
    criminalityScore: 5.35,
    rank: 79,
    region: 'europe',
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    year: 2023,
    criminalityScore: 5.33,
    rank: 80,
    region: 'europe',
  },
  {
    countryCode: 'BJ',
    countryName: 'Benin',
    year: 2023,
    criminalityScore: 5.32,
    rank: 81,
    region: 'africa',
  },
  {
    countryCode: 'KG',
    countryName: 'Kyrgyzstan',
    year: 2023,
    criminalityScore: 5.32,
    rank: 81,
    region: 'asia',
  },
  {
    countryCode: 'TG',
    countryName: 'Togo',
    year: 2023,
    criminalityScore: 5.23,
    rank: 83,
    region: 'africa',
  },
  {
    countryCode: 'KW',
    countryName: 'Kuwait',
    year: 2023,
    criminalityScore: 5.20,
    rank: 84,
    region: 'asia',
  },
  {
    countryCode: 'TT',
    countryName: 'Trinidad and Tobago',
    year: 2023,
    criminalityScore: 5.20,
    rank: 84,
    region: 'americas',
  },
  {
    countryCode: 'CL',
    countryName: 'Chile',
    year: 2023,
    criminalityScore: 5.18,
    rank: 86,
    region: 'americas',
  },
  {
    countryCode: 'AL',
    countryName: 'Albania',
    year: 2023,
    criminalityScore: 5.17,
    rank: 87,
    region: 'europe',
  },
  {
    countryCode: 'HR',
    countryName: 'Croatia',
    year: 2023,
    criminalityScore: 5.15,
    rank: 88,
    region: 'europe',
  },
  {
    countryCode: 'BD',
    countryName: 'Bangladesh',
    year: 2023,
    criminalityScore: 5.12,
    rank: 89,
    region: 'asia',
  },
  {
    countryCode: 'GW',
    countryName: 'Guinea-Bissau',
    year: 2023,
    criminalityScore: 5.10,
    rank: 90,
    region: 'africa',
  },
  {
    countryCode: 'IE',
    countryName: 'Ireland',
    year: 2023,
    criminalityScore: 5.08,
    rank: 91,
    region: 'europe',
  },
  {
    countryCode: 'EG',
    countryName: 'Egypt',
    year: 2023,
    criminalityScore: 5.05,
    rank: 92,
    region: 'africa',
  },
  {
    countryCode: 'MK',
    countryName: 'North Macedonia',
    year: 2023,
    criminalityScore: 5.03,
    rank: 93,
    region: 'europe',
  },
  {
    countryCode: 'DO',
    countryName: 'Dominican Republic',
    year: 2023,
    criminalityScore: 5.02,
    rank: 94,
    region: 'americas',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    year: 2023,
    criminalityScore: 5.00,
    rank: 95,
    region: 'americas',
  },
  {
    countryCode: 'MT',
    countryName: 'Malta',
    year: 2023,
    criminalityScore: 5.00,
    rank: 95,
    region: 'europe',
  },
  {
    countryCode: 'XK',
    countryName: 'Kosovo',
    year: 2023,
    criminalityScore: 4.97,
    rank: '-',
    region: 'europe',
  },
  {
    countryCode: 'NL',
    countryName: 'Netherlands',
    year: 2023,
    criminalityScore: 4.97,
    rank: 97,
    region: 'europe',
  },
  {
    countryCode: 'BH',
    countryName: 'Bahrain',
    year: 2023,
    criminalityScore: 4.95,
    rank: 98,
    region: 'asia',
  },
  {
    countryCode: 'BO',
    countryName: 'Bolivia',
    year: 2023,
    criminalityScore: 4.95,
    rank: 98,
    region: 'americas',
  },
  {
    countryCode: 'SL',
    countryName: 'Sierra Leone',
    year: 2023,
    criminalityScore: 4.95,
    rank: 98,
    region: 'africa',
  },
  {
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    year: 2023,
    criminalityScore: 4.95,
    rank: 98,
    region: 'asia',
  },
  {
    countryCode: 'JO',
    countryName: 'Jordan',
    year: 2023,
    criminalityScore: 4.93,
    rank: 102,
    region: 'asia',
  },
  {
    countryCode: 'LK',
    countryName: 'Sri Lanka',
    year: 2023,
    criminalityScore: 4.92,
    rank: 103,
    region: 'asia',
  },
  {
    countryCode: 'DZ',
    countryName: 'Algeria',
    year: 2023,
    criminalityScore: 4.88,
    rank: 104,
    region: 'africa',
  },
  {
    countryCode: 'PT',
    countryName: 'Portugal',
    year: 2023,
    criminalityScore: 4.88,
    rank: 104,
    region: 'europe',
  },
  {
    countryCode: 'BZ',
    countryName: 'Belize',
    year: 2023,
    criminalityScore: 4.87,
    rank: 106,
    region: 'americas',
  },
  {
    countryCode: 'BI',
    countryName: 'Burundi',
    year: 2023,
    criminalityScore: 4.87,
    rank: 106,
    region: 'africa',
  },
  {
    countryCode: 'CH',
    countryName: 'Switzerland',
    year: 2023,
    criminalityScore: 4.87,
    rank: 106,
    region: 'europe',
  },
  {
    countryCode: 'GA',
    countryName: 'Gabon',
    year: 2023,
    criminalityScore: 4.85,
    rank: 109,
    region: 'africa',
  },
  {
    countryCode: 'IL',
    countryName: 'Israel',
    year: 2023,
    criminalityScore: 4.85,
    rank: 109,
    region: 'asia',
  },
  {
    countryCode: 'KP',
    countryName: 'Korea, DPR',
    year: 2023,
    criminalityScore: 4.82,
    rank: 111,
    region: 'asia',
  },
  {
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    year: 2023,
    criminalityScore: 4.80,
    rank: 112,
    region: 'asia',
  },
  {
    countryCode: 'MA',
    countryName: 'Morocco',
    year: 2023,
    criminalityScore: 4.80,
    rank: 112,
    region: 'africa',
  },
  {
    countryCode: 'CG',
    countryName: 'Congo, Rep',
    year: 2023,
    criminalityScore: 4.78,
    rank: 114,
    region: 'africa',
  },
  {
    countryCode: 'SR',
    countryName: 'Suriname',
    year: 2023,
    criminalityScore: 4.77,
    rank: 115,
    region: 'americas',
  },
  {
    countryCode: 'ZM',
    countryName: 'Zambia',
    year: 2023,
    criminalityScore: 4.73,
    rank: 116,
    region: 'africa',
  },
  {
    countryCode: 'SK',
    countryName: 'Slovakia',
    year: 2023,
    criminalityScore: 4.72,
    rank: 117,
    region: 'europe',
  },
  {
    countryCode: 'SE',
    countryName: 'Sweden',
    year: 2023,
    criminalityScore: 4.70,
    rank: 118,
    region: 'europe',
  },
  {
    countryCode: 'CZ',
    countryName: 'Czech Republic',
    year: 2023,
    criminalityScore: 4.68,
    rank: 119,
    region: 'europe',
  },
  {
    countryCode: 'DJ',
    countryName: 'Djibouti',
    year: 2023,
    criminalityScore: 4.65,
    rank: 120,
    region: 'africa',
  },
  {
    countryCode: 'HU',
    countryName: 'Hungary',
    year: 2023,
    criminalityScore: 4.62,
    rank: 121,
    region: 'europe',
  },
  {
    countryCode: 'GN',
    countryName: 'Guinea',
    year: 2023,
    criminalityScore: 4.58,
    rank: 122,
    region: 'africa',
  },
  {
    countryCode: 'RO',
    countryName: 'Romania',
    year: 2023,
    criminalityScore: 4.58,
    rank: 122,
    region: 'europe',
  },
  {
    countryCode: 'GM',
    countryName: 'Gambia',
    year: 2023,
    criminalityScore: 4.53,
    rank: 124,
    region: 'africa',
  },
  {
    countryCode: 'MW',
    countryName: 'Malawi',
    year: 2023,
    criminalityScore: 4.48,
    rank: 125,
    region: 'africa',
  },
  {
    countryCode: 'PL',
    countryName: 'Poland',
    year: 2023,
    criminalityScore: 4.48,
    rank: 125,
    region: 'europe',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    year: 2023,
    criminalityScore: 4.47,
    rank: 127,
    region: 'asia',
  },
  {
    countryCode: 'TN',
    countryName: 'Tunisia',
    year: 2023,
    criminalityScore: 4.45,
    rank: 128,
    region: 'africa',
  },
  {
    countryCode: 'BE',
    countryName: 'Belgium',
    year: 2023,
    criminalityScore: 4.43,
    rank: 129,
    region: 'europe',
  },
  {
    countryCode: 'CY',
    countryName: 'Cyprus',
    year: 2023,
    criminalityScore: 4.43,
    rank: 129,
    region: 'europe',
  },
  {
    countryCode: 'KR',
    countryName: 'Korea, Rep.',
    year: 2023,
    criminalityScore: 4.43,
    rank: 129,
    region: 'asia',
  },
  {
    countryCode: 'OM',
    countryName: 'Oman',
    year: 2023,
    criminalityScore: 4.40,
    rank: 132,
    region: 'asia',
  },
  {
    countryCode: 'SB',
    countryName: 'Solomon Islands',
    year: 2023,
    criminalityScore: 4.40,
    rank: 132,
    region: 'oceania',
  },
  {
    countryCode: 'TM',
    countryName: 'Turkmenistan',
    year: 2023,
    criminalityScore: 4.40,
    rank: 132,
    region: 'asia',
  },
  {
    countryCode: 'GQ',
    countryName: 'Equatorial Guinea',
    year: 2023,
    criminalityScore: 4.38,
    rank: 135,
    region: 'africa',
  },
  {
    countryCode: 'SZ',
    countryName: 'Eswatini',
    year: 2023,
    criminalityScore: 4.38,
    rank: 135,
    region: 'africa',
  },
  {
    countryCode: 'MR',
    countryName: 'Mauritania',
    year: 2023,
    criminalityScore: 4.38,
    rank: 135,
    region: 'africa',
  },
  {
    countryCode: 'MU',
    countryName: 'Mauritius',
    year: 2023,
    criminalityScore: 4.37,
    rank: 138,
    region: 'africa',
  },
  {
    countryCode: 'SI',
    countryName: 'Slovenia',
    year: 2023,
    criminalityScore: 4.37,
    rank: 138,
    region: 'europe',
  },
  {
    countryCode: 'BW',
    countryName: 'Botswana',
    year: 2023,
    criminalityScore: 4.35,
    rank: 140,
    region: 'africa',
  },
  {
    countryCode: 'NA',
    countryName: 'Namibia',
    year: 2023,
    criminalityScore: 4.30,
    rank: 141,
    region: 'africa',
  },
  {
    countryCode: 'CV',
    countryName: 'Cabo Verde',
    year: 2023,
    criminalityScore: 4.28,
    rank: 142,
    region: 'africa',
  },
  {
    countryCode: 'JP',
    countryName: 'Japan',
    year: 2023,
    criminalityScore: 4.28,
    rank: 142,
    region: 'asia',
  },
  {
    countryCode: 'MV',
    countryName: 'Maldives',
    year: 2023,
    criminalityScore: 4.27,
    rank: 144,
    region: 'asia',
  },
  {
    countryCode: 'EE',
    countryName: 'Estonia',
    year: 2023,
    criminalityScore: 4.25,
    rank: 145,
    region: 'europe',
  },
  {
    countryCode: 'FJ',
    countryName: 'Fiji',
    year: 2023,
    criminalityScore: 4.15,
    rank: 146,
    region: 'oceania',
  },
  {
    countryCode: 'AT',
    countryName: 'Austria',
    year: 2023,
    criminalityScore: 4.13,
    rank: 147,
    region: 'europe',
  },
  {
    countryCode: 'MN',
    countryName: 'Mongolia',
    year: 2023,
    criminalityScore: 4.12,
    rank: 148,
    region: 'asia',
  },
  {
    countryCode: 'NZ',
    countryName: 'New Zealand',
    year: 2023,
    criminalityScore: 4.08,
    rank: 149,
    region: 'oceania',
  },
  {
    countryCode: 'TL',
    countryName: 'Timor-Leste',
    year: 2023,
    criminalityScore: 4.08,
    rank: 149,
    region: 'asia',
  },
  {
    countryCode: 'DK',
    countryName: 'Denmark',
    year: 2023,
    criminalityScore: 4.02,
    rank: 151,
    region: 'europe',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    year: 2023,
    criminalityScore: 4.00,
    rank: 152,
    region: 'oceania',
  },
  {
    countryCode: 'ER',
    countryName: 'Eritrea',
    year: 2023,
    criminalityScore: 3.97,
    rank: 153,
    region: 'africa',
  },
  {
    countryCode: 'KM',
    countryName: 'Comoros',
    year: 2023,
    criminalityScore: 3.92,
    rank: 154,
    region: 'africa',
  },
  {
    countryCode: 'LS',
    countryName: 'Lesotho',
    year: 2023,
    criminalityScore: 3.92,
    rank: 154,
    region: 'africa',
  },
  {
    countryCode: 'BT',
    countryName: 'Bhutan',
    year: 2023,
    criminalityScore: 3.90,
    rank: 156,
    region: 'asia',
  },
  {
    countryCode: 'LV',
    countryName: 'Latvia',
    year: 2023,
    criminalityScore: 3.90,
    rank: 156,
    region: 'europe',
  },
  {
    countryCode: 'LT',
    countryName: 'Lithuania',
    year: 2023,
    criminalityScore: 3.90,
    rank: 156,
    region: 'europe',
  },
  {
    countryCode: 'SC',
    countryName: 'Seychelles',
    year: 2023,
    criminalityScore: 3.90,
    rank: 156,
    region: 'africa',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    year: 2023,
    criminalityScore: 3.88,
    rank: 160,
    region: 'americas',
  },
  {
    countryCode: 'BS',
    countryName: 'Bahamas',
    year: 2023,
    criminalityScore: 3.75,
    rank: 161,
    region: 'americas',
  },
  {
    countryCode: 'NO',
    countryName: 'Norway',
    year: 2023,
    criminalityScore: 3.75,
    rank: 161,
    region: 'europe',
  },
  {
    countryCode: 'TO',
    countryName: 'Tonga',
    year: 2023,
    criminalityScore: 3.70,
    rank: 163,
    region: 'oceania',
  },
  {
    countryCode: 'GE',
    countryName: 'Georgia',
    year: 2023,
    criminalityScore: 3.60,
    rank: 164,
    region: 'asia',
  },
  {
    countryCode: 'RW',
    countryName: 'Rwanda',
    year: 2023,
    criminalityScore: 3.60,
    rank: 164,
    region: 'africa',
  },
  {
    countryCode: 'LC',
    countryName: 'St. Lucia',
    year: 2023,
    criminalityScore: 3.53,
    rank: 166,
    region: 'americas',
  },
  {
    countryCode: 'KN',
    countryName: 'St. Kitts and Nevis',
    year: 2023,
    criminalityScore: 3.52,
    rank: 167,
    region: 'americas',
  },
  {
    countryCode: 'SM',
    countryName: 'San Marino',
    year: 2023,
    criminalityScore: 3.48,
    rank: 168,
    region: 'europe',
  },
  {
    countryCode: 'SG',
    countryName: 'Singapore',
    year: 2023,
    criminalityScore: 3.47,
    rank: 169,
    region: 'asia',
  },
  {
    countryCode: 'CU',
    countryName: 'Cuba',
    year: 2023,
    criminalityScore: 3.37,
    rank: 170,
    region: 'americas',
  },
  {
    countryCode: 'IS',
    countryName: 'Iceland',
    year: 2023,
    criminalityScore: 3.37,
    rank: 170,
    region: 'europe',
  },
  {
    countryCode: 'AD',
    countryName: 'Andorra',
    year: 2023,
    criminalityScore: 3.22,
    rank: 172,
    region: 'europe',
  },
  {
    countryCode: 'UY',
    countryName: 'Uruguay',
    year: 2023,
    criminalityScore: 3.22,
    rank: 172,
    region: 'americas',
  },
  {
    countryCode: 'VC',
    countryName: 'St. Vincent and the Grenadines',
    year: 2023,
    criminalityScore: 3.08,
    rank: 174,
    region: 'americas',
  },
  {
    countryCode: 'BB',
    countryName: 'Barbados',
    year: 2023,
    criminalityScore: 3.07,
    rank: 175,
    region: 'americas',
  },
  {
    countryCode: 'FM',
    countryName: 'Micronesia (Federated States of)',
    year: 2023,
    criminalityScore: 3.00,
    rank: 176,
    region: 'oceania',
  },
  {
    countryCode: 'AG',
    countryName: 'Antigua and Barbuda',
    year: 2023,
    criminalityScore: 2.98,
    rank: 177,
    region: 'americas',
  },
  {
    countryCode: 'FI',
    countryName: 'Finland',
    year: 2023,
    criminalityScore: 2.98,
    rank: 177,
    region: 'europe',
  },
  {
    countryCode: 'GD',
    countryName: 'Grenada',
    year: 2023,
    criminalityScore: 2.93,
    rank: 179,
    region: 'americas',
  },
  {
    countryCode: 'BN',
    countryName: 'Brunei',
    year: 2023,
    criminalityScore: 2.85,
    rank: 180,
    region: 'asia',
  },
  {
    countryCode: 'LU',
    countryName: 'Luxembourg',
    year: 2023,
    criminalityScore: 2.85,
    rank: 180,
    region: 'europe',
  },
  {
    countryCode: 'AM',
    countryName: 'Armenia',
    year: 2023,
    criminalityScore: 2.82,
    rank: 182,
    region: 'asia',
  },
  {
    countryCode: 'PW',
    countryName: 'Palau',
    year: 2023,
    criminalityScore: 2.70,
    rank: 183,
    region: 'oceania',
  },
  {
    countryCode: 'DM',
    countryName: 'Dominica',
    year: 2023,
    criminalityScore: 2.63,
    rank: 184,
    region: 'americas',
  },
  {
    countryCode: 'MC',
    countryName: 'Monaco',
    year: 2023,
    criminalityScore: 2.58,
    rank: 185,
    region: 'europe',
  },
  {
    countryCode: 'MH',
    countryName: 'Marshall Islands',
    year: 2023,
    criminalityScore: 2.52,
    rank: 186,
    region: 'oceania',
  },
  {
    countryCode: 'KI',
    countryName: 'Kiribati',
    year: 2023,
    criminalityScore: 2.45,
    rank: 187,
    region: 'oceania',
  },
  {
    countryCode: 'WS',
    countryName: 'Samoa',
    year: 2023,
    criminalityScore: 2.43,
    rank: 188,
    region: 'oceania',
  },
  {
    countryCode: 'VU',
    countryName: 'Vanuatu',
    year: 2023,
    criminalityScore: 2.43,
    rank: 188,
    region: 'oceania',
  },
  {
    countryCode: 'LI',
    countryName: 'Liechtenstein',
    year: 2023,
    criminalityScore: 2.27,
    rank: 190,
    region: 'europe',
  },
  {
    countryCode: 'NR',
    countryName: 'Nauru',
    year: 2023,
    criminalityScore: 2.05,
    rank: 191,
    region: 'oceania',
  },
  {
    countryCode: 'ST',
    countryName: 'São Tomé and Príncipe',
    year: 2023,
    criminalityScore: 1.70,
    rank: 192,
    region: 'africa',
  },
  {
    countryCode: 'TV',
    countryName: 'Tuvalu',
    year: 2023,
    criminalityScore: 1.62,
    rank: 193,
    region: 'oceania',
  },
];

// Criminal Markets data from pages 212-221
export const criminalMarketsData = [
  // Top criminal markets scores
  {
    countryCode: 'MX',
    markets: {
      average: 8.13,
      humanTrafficking: 8.0,
      humanSmuggling: 9.0,
      extortionProtection: 9.0,
      armsTrafficking: 8.5,
      tradeCounterfeitGoods: 8.5,
      illicitTradeExciseGoods: 7.0,
      floraFaunaCrimes: 7.5,
      nonRenewableResourceCrimes: 7.0,
      heroinTrade: 7.5,
      cocaineTrade: 8.0,
      cannabisTrade: 9.0,
      syntheticDrugTrade: 8.0,
      cyberDependentCrimes: 9.0,
      financialCrimes: 8.5,
    },
  },
  {
    countryCode: 'MM',
    markets: {
      average: 7.70,
      humanTrafficking: 8.5,
      humanSmuggling: 8.0,
      extortionProtection: 7.5,
      armsTrafficking: 9.0,
      tradeCounterfeitGoods: 6.0,
      illicitTradeExciseGoods: 7.0,
      floraFaunaCrimes: 8.5,
      nonRenewableResourceCrimes: 8.5,
      heroinTrade: 9.0,
      cocaineTrade: 9.5,
      cannabisTrade: 3.5,
      syntheticDrugTrade: 4.5,
      cyberDependentCrimes: 10.0,
      financialCrimes: 7.5,
    },
  },
  // Continue with more markets data...
];

// Criminal Actors data from pages 222-226
export const criminalActorsData = [
  {
    countryCode: 'MM',
    actors: {
      average: 8.60,
      mafiaStyleGroups: 9.5,
      criminalNetworks: 8.0,
      stateEmbeddedActors: 9.0,
      foreignActors: 9.0,
      privateActors: 7.5,
    },
  },
  {
    countryCode: 'CD',
    actors: {
      average: 8.50,
      mafiaStyleGroups: 9.0,
      criminalNetworks: 9.0,
      stateEmbeddedActors: 9.0,
      foreignActors: 9.0,
      privateActors: 6.5,
    },
  },
  // Continue with more actors data...
];

// Resilience scores from pages 228-237
export const resilienceData = [
  {
    countryCode: 'FI',
    resilience: {
      average: 8.63,
      politicalLeadership: 9.0,
      governmentTransparency: 9.0,
      internationalCooperation: 9.0,
      nationalPolicies: 8.5,
      judicialSystem: 8.0,
      lawEnforcement: 8.5,
      territorialIntegrity: 9.0,
      antiMoneyLaundering: 8.5,
      economicRegulatory: 9.0,
      victimSupport: 8.0,
      prevention: 8.5,
      nonStateActors: 8.5,
    },
  },
  {
    countryCode: 'LI',
    resilience: {
      average: 8.46,
      politicalLeadership: 9.0,
      governmentTransparency: 8.0,
      internationalCooperation: 7.5,
      nationalPolicies: 9.0,
      judicialSystem: 9.0,
      lawEnforcement: 8.5,
      territorialIntegrity: 9.5,
      antiMoneyLaundering: 5.0,
      economicRegulatory: 8.5,
      victimSupport: 9.5,
      prevention: 9.5,
      nonStateActors: 8.5,
    },
  },
  // Continue with more resilience data...
];
