import type { CollectionConfig } from 'payload'

export const CrimeIndexScores: CollectionConfig = {
  slug: 'crime-index-scores',
  labels: {
    singular: 'Crime Index Score',
    plural: 'Crime Index Scores',
  },
  admin: {
    useAsTitle: 'year',
    defaultColumns: ['country', 'year', 'criminalityScore', 'rank'],
    group: 'Data Source',
  },
  fields: [
    {
      name: 'country',
      type: 'relationship',
      relationTo: 'countries',
      required: true,
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'year',
      type: 'number',
      required: true,
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'criminalityScore',
      type: 'number',
      required: true,
      min: 0,
      max: 10,
      admin: {
        step: 0.01,
      },
    },
    {
      name: 'resilienceScore',
      type: 'number',
      required: true,
      min: 0,
      max: 10,
      admin: {
        step: 0.01,
      },
    },
    {
      name: 'rank',
      type: 'number',
      required: false,
      min: 1,
      max: 200,
    },
    {
      name: 'region',
      type: 'text',
      required: true,
    },
    {
      name: 'criminalMarkets',
      type: 'group',
      fields: [
        {
          name: 'humanTrafficking',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'humanSmuggling',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'extortionProtection',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'armsTrafficking',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'counterfeiting',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'illicitDrugs',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'environmentalCrimes',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'heistRobbery',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'financialCrimes',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'cyberCrimes',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'privateCorruption',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'publicCorruption',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'heroinTrade',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'syntheticDrugTrade',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
      ],
    },
    {
      name: 'criminalActors',
      type: 'group',
      fields: [
        {
          name: 'mafiaStyle',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'criminalNetworks',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'stateActors',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'foreignActors',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'privateActors',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
      ],
    },
    {
      name: 'resilience',
      type: 'group',
      fields: [
        {
          name: 'politicalLeadership',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'governmentTransparency',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'internationalCooperation',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'nationalPolicies',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'judicialSystem',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'lawEnforcement',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'territorialIntegrity',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'antiMoneyLaundering',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'economicRegulation',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'victimSupport',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'prevention',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
        {
          name: 'nonStateActors',
          type: 'number',
          min: 0,
          max: 10,
          admin: { step: 0.5 },
        },
      ],
    },
  ],
  indexes: [
    {
      fields: ['country', 'year'],
      unique: true,
    },
  ],
}