// Airport data from various sources
export const airportsData = [
  // Major International Airports
  {
    name: 'Hartsfield-Jackson Atlanta International Airport',
    iata: 'ATL',
    icao: 'KATL',
    city: 'Atlanta',
    countryCode: 'US',
    regionCode: 'GA',
    latitude: 33.6367,
    longitude: -84.4281,
    elevation: 1026,
    timezoneCode: 'america-new-york',
    type: 'large',
  },
  {
    name: 'Beijing Capital International Airport',
    iata: 'PEK',
    icao: 'ZBAA',
    city: 'Beijing',
    countryCode: 'CN',
    regionCode: 'BJ',
    latitude: 40.0801,
    longitude: 116.5846,
    elevation: 116,
    timezoneCode: 'asia-shanghai',
    type: 'large',
  },
  {
    name: 'Dubai International Airport',
    iata: 'DXB',
    icao: 'OMDB',
    city: 'Dubai',
    countryCode: 'AE',
    regionCode: 'DU',
    latitude: 25.2528,
    longitude: 55.3644,
    elevation: 62,
    timezoneCode: 'asia-dubai',
    type: 'large',
  },
  {
    name: 'Los Angeles International Airport',
    iata: 'LAX',
    icao: 'KLAX',
    city: 'Los Angeles',
    countryCode: 'US',
    regionCode: 'CA',
    latitude: 33.9425,
    longitude: -118.4081,
    elevation: 125,
    timezoneCode: 'america-los-angeles',
    type: 'large',
  },
  {
    name: "Chicago O'Hare International Airport",
    iata: 'ORD',
    icao: 'KORD',
    city: 'Chicago',
    countryCode: 'US',
    regionCode: 'IL',
    latitude: 41.9786,
    longitude: -87.9048,
    elevation: 672,
    timezoneCode: 'america-chicago',
    type: 'large',
  },
  {
    name: 'London Heathrow Airport',
    iata: 'LHR',
    icao: 'EGLL',
    city: 'London',
    countryCode: 'GB',
    regionCode: 'ENG',
    latitude: 51.4700,
    longitude: -0.4543,
    elevation: 83,
    timezoneCode: 'europe-london',
    type: 'large',
  },
  {
    name: 'Tokyo Haneda Airport',
    iata: 'HND',
    icao: 'RJTT',
    city: 'Tokyo',
    countryCode: 'JP',
    regionCode: '13',
    latitude: 35.5533,
    longitude: 139.7811,
    elevation: 21,
    timezoneCode: 'asia-tokyo',
    type: 'large',
  },
  {
    name: 'Charles de Gaulle Airport',
    iata: 'CDG',
    icao: 'LFPG',
    city: 'Paris',
    countryCode: 'FR',
    regionCode: 'IDF',
    latitude: 49.0097,
    longitude: 2.5479,
    elevation: 392,
    timezoneCode: 'europe-paris',
    type: 'large',
  },
  {
    name: 'Dallas/Fort Worth International Airport',
    iata: 'DFW',
    icao: 'KDFW',
    city: 'Dallas',
    countryCode: 'US',
    regionCode: 'TX',
    latitude: 32.8998,
    longitude: -97.0403,
    elevation: 607,
    timezoneCode: 'america-chicago',
    type: 'large',
  },
  {
    name: 'Amsterdam Airport Schiphol',
    iata: 'AMS',
    icao: 'EHAM',
    city: 'Amsterdam',
    countryCode: 'NL',
    regionCode: 'NH',
    latitude: 52.3086,
    longitude: 4.7639,
    elevation: -11,
    timezoneCode: 'europe-amsterdam',
    type: 'large',
  },
  {
    name: 'Frankfurt Airport',
    iata: 'FRA',
    icao: 'EDDF',
    city: 'Frankfurt',
    countryCode: 'DE',
    regionCode: 'HE',
    latitude: 50.0333,
    longitude: 8.5706,
    elevation: 364,
    timezoneCode: 'europe-berlin',
    type: 'large',
  },
  {
    name: 'Denver International Airport',
    iata: 'DEN',
    icao: 'KDEN',
    city: 'Denver',
    countryCode: 'US',
    regionCode: 'CO',
    latitude: 39.8617,
    longitude: -104.6732,
    elevation: 5431,
    timezoneCode: 'america-denver',
    type: 'large',
  },
  {
    name: 'Singapore Changi Airport',
    iata: 'SIN',
    icao: 'WSSS',
    city: 'Singapore',
    countryCode: 'SG',
    regionCode: 'SG',
    latitude: 1.3644,
    longitude: 103.9915,
    elevation: 22,
    timezoneCode: 'asia-singapore',
    type: 'large',
  },
  {
    name: 'Incheon International Airport',
    iata: 'ICN',
    icao: 'RKSI',
    city: 'Seoul',
    countryCode: 'KR',
    regionCode: '28',
    latitude: 37.4602,
    longitude: 126.4407,
    elevation: 23,
    timezoneCode: 'asia-seoul',
    type: 'large',
  },
  {
    name: 'Suvarnabhumi Airport',
    iata: 'BKK',
    icao: 'VTBS',
    city: 'Bangkok',
    countryCode: 'TH',
    regionCode: '10',
    latitude: 13.6900,
    longitude: 100.7501,
    elevation: 5,
    timezoneCode: 'asia-bangkok',
    type: 'large',
  },
  {
    name: 'Indira Gandhi International Airport',
    iata: 'DEL',
    icao: 'VIDP',
    city: 'New Delhi',
    countryCode: 'IN',
    regionCode: 'DL',
    latitude: 28.5665,
    longitude: 77.1031,
    elevation: 777,
    timezoneCode: 'asia-kolkata',
    type: 'large',
  },
  {
    name: 'John F. Kennedy International Airport',
    iata: 'JFK',
    icao: 'KJFK',
    city: 'New York',
    countryCode: 'US',
    regionCode: 'NY',
    latitude: 40.6413,
    longitude: -73.7781,
    elevation: 13,
    timezoneCode: 'america-new-york',
    type: 'large',
  },
  {
    name: 'Hong Kong International Airport',
    iata: 'HKG',
    icao: 'VHHH',
    city: 'Hong Kong',
    countryCode: 'HK',
    regionCode: 'HK',
    latitude: 22.3080,
    longitude: 113.9185,
    elevation: 28,
    timezoneCode: 'asia-shanghai',
    type: 'large',
  },
  {
    name: 'Shanghai Pudong International Airport',
    iata: 'PVG',
    icao: 'ZSPD',
    city: 'Shanghai',
    countryCode: 'CN',
    regionCode: 'SH',
    latitude: 31.1443,
    longitude: 121.8083,
    elevation: 13,
    timezoneCode: 'asia-shanghai',
    type: 'large',
  },
  {
    name: 'Guangzhou Baiyun International Airport',
    iata: 'CAN',
    icao: 'ZGGG',
    city: 'Guangzhou',
    countryCode: 'CN',
    regionCode: 'GD',
    latitude: 23.3925,
    longitude: 113.2988,
    elevation: 50,
    timezoneCode: 'asia-shanghai',
    type: 'large',
  },
  {
    name: 'Miami International Airport',
    iata: 'MIA',
    icao: 'KMIA',
    city: 'Miami',
    countryCode: 'US',
    regionCode: 'FL',
    latitude: 25.7953,
    longitude: -80.2901,
    elevation: 8,
    timezoneCode: 'america-new-york',
    type: 'large',
  },
  {
    name: 'Munich Airport',
    iata: 'MUC',
    icao: 'EDDM',
    city: 'Munich',
    countryCode: 'DE',
    regionCode: 'BY',
    latitude: 48.3538,
    longitude: 11.7861,
    elevation: 1487,
    timezoneCode: 'europe-berlin',
    type: 'large',
  },
  {
    name: 'Sydney Kingsford Smith International Airport',
    iata: 'SYD',
    icao: 'YSSY',
    city: 'Sydney',
    countryCode: 'AU',
    regionCode: 'NSW',
    latitude: -33.9461,
    longitude: 151.1772,
    elevation: 21,
    timezoneCode: 'australia-sydney',
    type: 'large',
  },
  {
    name: 'Toronto Pearson International Airport',
    iata: 'YYZ',
    icao: 'CYYZ',
    city: 'Toronto',
    countryCode: 'CA',
    regionCode: 'ON',
    latitude: 43.6772,
    longitude: -79.6306,
    elevation: 569,
    timezoneCode: 'america-toronto',
    type: 'large',
  },
  {
    name: 'São Paulo–Guarulhos International Airport',
    iata: 'GRU',
    icao: 'SBGR',
    city: 'São Paulo',
    countryCode: 'BR',
    regionCode: 'SP',
    latitude: -23.4356,
    longitude: -46.4731,
    elevation: 2459,
    timezoneCode: 'america-sao-paulo',
    type: 'large',
  },
  {
    name: 'Istanbul Airport',
    iata: 'IST',
    icao: 'LTFM',
    city: 'Istanbul',
    countryCode: 'TR',
    regionCode: '34',
    latitude: 41.2753,
    longitude: 28.7519,
    elevation: 325,
    timezoneCode: 'europe-istanbul',
    type: 'large',
  },
  {
    name: 'Madrid-Barajas Airport',
    iata: 'MAD',
    icao: 'LEMD',
    city: 'Madrid',
    countryCode: 'ES',
    regionCode: 'MD',
    latitude: 40.4719,
    longitude: -3.5626,
    elevation: 2077,
    timezoneCode: 'europe-madrid',
    type: 'large',
  },
  {
    name: 'Barcelona–El Prat Airport',
    iata: 'BCN',
    icao: 'LEBL',
    city: 'Barcelona',
    countryCode: 'ES',
    regionCode: 'CT',
    latitude: 41.2971,
    longitude: 2.0785,
    elevation: 12,
    timezoneCode: 'europe-madrid',
    type: 'large',
  },
  {
    name: 'Rome Fiumicino Airport',
    iata: 'FCO',
    icao: 'LIRF',
    city: 'Rome',
    countryCode: 'IT',
    regionCode: 'LAZ',
    latitude: 41.8045,
    longitude: 12.2508,
    elevation: 15,
    timezoneCode: 'europe-rome',
    type: 'large',
  },
  {
    name: 'Zurich Airport',
    iata: 'ZRH',
    icao: 'LSZH',
    city: 'Zurich',
    countryCode: 'CH',
    regionCode: 'ZH',
    latitude: 47.4647,
    longitude: 8.5492,
    elevation: 1416,
    timezoneCode: 'europe-zurich',
    type: 'large',
  },
  {
    name: 'Vienna International Airport',
    iata: 'VIE',
    icao: 'LOWW',
    city: 'Vienna',
    countryCode: 'AT',
    regionCode: '9',
    latitude: 48.1103,
    longitude: 16.5697,
    elevation: 600,
    timezoneCode: 'europe-vienna',
    type: 'large',
  },
  {
    name: 'Stockholm Arlanda Airport',
    iata: 'ARN',
    icao: 'ESSA',
    city: 'Stockholm',
    countryCode: 'SE',
    regionCode: 'AB',
    latitude: 59.6519,
    longitude: 17.9186,
    elevation: 137,
    timezoneCode: 'europe-stockholm',
    type: 'large',
  },
  {
    name: 'Copenhagen Airport',
    iata: 'CPH',
    icao: 'EKCH',
    city: 'Copenhagen',
    countryCode: 'DK',
    regionCode: '84',
    latitude: 55.6181,
    longitude: 12.6561,
    elevation: 17,
    timezoneCode: 'europe-copenhagen',
    type: 'large',
  },
  {
    name: 'Oslo Airport',
    iata: 'OSL',
    icao: 'ENGM',
    city: 'Oslo',
    countryCode: 'NO',
    regionCode: '30',
    latitude: 60.1939,
    longitude: 11.1004,
    elevation: 681,
    timezoneCode: 'europe-oslo',
    type: 'large',
  },
  {
    name: 'Helsinki-Vantaa Airport',
    iata: 'HEL',
    icao: 'EFHK',
    city: 'Helsinki',
    countryCode: 'FI',
    regionCode: '18',
    latitude: 60.3172,
    longitude: 24.9633,
    elevation: 179,
    timezoneCode: 'europe-helsinki',
    type: 'large',
  },
  {
    name: 'Athens International Airport',
    iata: 'ATH',
    icao: 'LGAV',
    city: 'Athens',
    countryCode: 'GR',
    regionCode: 'I',
    latitude: 37.9364,
    longitude: 23.9445,
    elevation: 308,
    timezoneCode: 'europe-athens',
    type: 'large',
  },
  {
    name: 'Dublin Airport',
    iata: 'DUB',
    icao: 'EIDW',
    city: 'Dublin',
    countryCode: 'IE',
    regionCode: 'L',
    latitude: 53.4264,
    longitude: -6.2499,
    elevation: 242,
    timezoneCode: 'europe-dublin',
    type: 'large',
  },
  {
    name: 'Brussels Airport',
    iata: 'BRU',
    icao: 'EBBR',
    city: 'Brussels',
    countryCode: 'BE',
    regionCode: 'VLG',
    latitude: 50.9014,
    longitude: 4.4844,
    elevation: 184,
    timezoneCode: 'europe-brussels',
    type: 'large',
  },
  {
    name: 'Warsaw Chopin Airport',
    iata: 'WAW',
    icao: 'EPWA',
    city: 'Warsaw',
    countryCode: 'PL',
    regionCode: 'MZ',
    latitude: 52.1657,
    longitude: 20.9671,
    elevation: 362,
    timezoneCode: 'europe-warsaw',
    type: 'large',
  },
  {
    name: 'Cairo International Airport',
    iata: 'CAI',
    icao: 'HECA',
    city: 'Cairo',
    countryCode: 'EG',
    regionCode: 'C',
    latitude: 30.1219,
    longitude: 31.4056,
    elevation: 382,
    timezoneCode: 'africa-cairo',
    type: 'large',
  },
  {
    name: 'OR Tambo International Airport',
    iata: 'JNB',
    icao: 'FAOR',
    city: 'Johannesburg',
    countryCode: 'ZA',
    regionCode: 'GP',
    latitude: -26.1367,
    longitude: 28.2411,
    elevation: 5558,
    timezoneCode: 'africa-johannesburg',
    type: 'large',
  },
  {
    name: 'Ben Gurion Airport',
    iata: 'TLV',
    icao: 'LLBG',
    city: 'Tel Aviv',
    countryCode: 'IL',
    regionCode: 'M',
    latitude: 32.0117,
    longitude: 34.8864,
    elevation: 135,
    timezoneCode: 'asia-jerusalem',
    type: 'large',
  },
  {
    name: 'King Abdulaziz International Airport',
    iata: 'JED',
    icao: 'OEJN',
    city: 'Jeddah',
    countryCode: 'SA',
    regionCode: '02',
    latitude: 21.6796,
    longitude: 39.1565,
    elevation: 48,
    timezoneCode: 'asia-riyadh',
    type: 'large',
  },
  {
    name: 'Mexico City International Airport',
    iata: 'MEX',
    icao: 'MMMX',
    city: 'Mexico City',
    countryCode: 'MX',
    regionCode: 'CMX',
    latitude: 19.4363,
    longitude: -99.0721,
    elevation: 7316,
    timezoneCode: 'america-mexico-city',
    type: 'large',
  },
  {
    name: 'Jorge Chávez International Airport',
    iata: 'LIM',
    icao: 'SPJC',
    city: 'Lima',
    countryCode: 'PE',
    regionCode: 'LMA',
    latitude: -12.0219,
    longitude: -77.1143,
    elevation: 113,
    timezoneCode: 'america-lima',
    type: 'large',
  },
  {
    name: 'El Dorado International Airport',
    iata: 'BOG',
    icao: 'SKBO',
    city: 'Bogotá',
    countryCode: 'CO',
    regionCode: 'DC',
    latitude: 4.7016,
    longitude: -74.1469,
    elevation: 8361,
    timezoneCode: 'america-bogota',
    type: 'large',
  },
  {
    name: 'Ministro Pistarini International Airport',
    iata: 'EZE',
    icao: 'SAEZ',
    city: 'Buenos Aires',
    countryCode: 'AR',
    regionCode: 'B',
    latitude: -34.8222,
    longitude: -58.5358,
    elevation: 67,
    timezoneCode: 'america-argentina-buenos-aires',
    type: 'large',
  },
  {
    name: 'Arturo Merino Benítez International Airport',
    iata: 'SCL',
    icao: 'SCEL',
    city: 'Santiago',
    countryCode: 'CL',
    regionCode: 'RM',
    latitude: -33.3930,
    longitude: -70.7858,
    elevation: 1555,
    timezoneCode: 'america-santiago',
    type: 'large',
  },
  {
    name: 'Auckland Airport',
    iata: 'AKL',
    icao: 'NZAA',
    city: 'Auckland',
    countryCode: 'NZ',
    regionCode: 'AUK',
    latitude: -37.0082,
    longitude: 174.7850,
    elevation: 23,
    timezoneCode: 'pacific-auckland',
    type: 'large',
  },
  {
    name: 'Melbourne Airport',
    iata: 'MEL',
    icao: 'YMML',
    city: 'Melbourne',
    countryCode: 'AU',
    regionCode: 'VIC',
    latitude: -37.6733,
    longitude: 144.8430,
    elevation: 434,
    timezoneCode: 'australia-melbourne',
    type: 'large',
  },
]
