// Country data with relationships to currencies and languages
// Based on ISO 3166-1 and data from multiple sources
export const countriesData = [
  {
    name: 'United States',
    code: 'US',
    code3: 'USA',
    continent: 'north-america',
    capital: 'Washington, D.C.',
    countryCode: '+1',
    isoCode: '840',
    demonym: 'American',
    currencyCode: 'USD',
    languageCodes: ['en'],
    timezoneCode: 'america-new-york',
  },
  {
    name: 'Hong Kong',
    code: 'HK',
    code3: 'HKG',
    continent: 'asia',
    capital: 'Hong Kong',
    countryCode: '+852',
    isoCode: '344',
    demonym: 'Hong Konger',
    currencyCode: 'HKD',
    languageCodes: ['zh', 'en'],
    timezoneCode: 'asia-hong-kong',
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    code3: 'GBR',
    continent: 'europe',
    capital: 'London',
    countryCode: '+44',
    isoCode: '826',
    demonym: 'British',
    currencyCode: 'GBP',
    languageCodes: ['en'],
    timezoneCode: 'europe-london',
  },
  {
    name: 'Canada',
    code: 'CA',
    code3: 'CAN',
    continent: 'north-america',
    capital: 'Ottawa',
    countryCode: '+1',
    isoCode: '124',
    demonym: 'Canadian',
    currencyCode: 'CAD',
    languageCodes: ['en', 'fr'],
    timezoneCode: 'america-toronto',
  },
  {
    name: 'Australia',
    code: 'AU',
    code3: 'AUS',
    continent: 'oceania-australia',
    capital: 'Canberra',
    countryCode: '+61',
    isoCode: '036',
    demonym: 'Australian',
    currencyCode: 'AUD',
    languageCodes: ['en'],
    timezoneCode: 'australia-sydney',
  },
  {
    name: 'Germany',
    code: 'DE',
    code3: 'DEU',
    continent: 'europe',
    capital: 'Berlin',
    countryCode: '+49',
    isoCode: '276',
    demonym: 'German',
    currencyCode: 'EUR',
    languageCodes: ['de'],
    timezoneCode: 'europe-berlin',
  },
  {
    name: 'France',
    code: 'FR',
    code3: 'FRA',
    continent: 'europe',
    capital: 'Paris',
    countryCode: '+33',
    isoCode: '250',
    demonym: 'French',
    currencyCode: 'EUR',
    languageCodes: ['fr'],
    timezoneCode: 'europe-paris',
  },
  {
    name: 'Italy',
    code: 'IT',
    code3: 'ITA',
    continent: 'europe',
    capital: 'Rome',
    countryCode: '+39',
    isoCode: '380',
    demonym: 'Italian',
    currencyCode: 'EUR',
    languageCodes: ['it'],
    timezoneCode: 'europe-rome',
  },
  {
    name: 'Spain',
    code: 'ES',
    code3: 'ESP',
    continent: 'europe',
    capital: 'Madrid',
    countryCode: '+34',
    isoCode: '724',
    demonym: 'Spanish',
    currencyCode: 'EUR',
    languageCodes: ['es', 'ca', 'gl', 'eu'],
    timezoneCode: 'europe-madrid',
  },
  {
    name: 'Japan',
    code: 'JP',
    code3: 'JPN',
    continent: 'asia',
    capital: 'Tokyo',
    countryCode: '+81',
    isoCode: '392',
    demonym: 'Japanese',
    currencyCode: 'JPY',
    languageCodes: ['ja'],
    timezoneCode: 'asia-tokyo',
  },
  {
    name: 'China',
    code: 'CN',
    code3: 'CHN',
    continent: 'asia',
    capital: 'Beijing',
    countryCode: '+86',
    isoCode: '156',
    demonym: 'Chinese',
    currencyCode: 'CNY',
    languageCodes: ['zh'],
    timezoneCode: 'asia-shanghai',
  },
  {
    name: 'India',
    code: 'IN',
    code3: 'IND',
    continent: 'asia',
    capital: 'New Delhi',
    countryCode: '+91',
    isoCode: '356',
    demonym: 'Indian',
    currencyCode: 'INR',
    languageCodes: ['hi', 'en', 'bn', 'te', 'mr', 'ta', 'ur', 'gu', 'kn', 'ml', 'or', 'pa', 'as', 'ks', 'sd', 'sa'],
    timezoneCode: 'asia-kolkata',
  },
  {
    name: 'Brazil',
    code: 'BR',
    code3: 'BRA',
    continent: 'south-america',
    capital: 'Brasília',
    countryCode: '+55',
    isoCode: '076',
    demonym: 'Brazilian',
    currencyCode: 'BRL',
    languageCodes: ['pt'],
    timezoneCode: 'america-sao-paulo',
  },
  {
    name: 'Mexico',
    code: 'MX',
    code3: 'MEX',
    continent: 'north-america',
    capital: 'Mexico City',
    countryCode: '+52',
    isoCode: '484',
    demonym: 'Mexican',
    currencyCode: 'MXN',
    languageCodes: ['es'],
    timezoneCode: 'america-mexico-city',
  },
  {
    name: 'Argentina',
    code: 'AR',
    code3: 'ARG',
    continent: 'south-america',
    capital: 'Buenos Aires',
    countryCode: '+54',
    isoCode: '032',
    demonym: 'Argentinian',
    currencyCode: 'ARS',
    languageCodes: ['es'],
    timezoneCode: 'america-argentina-buenos-aires',
  },
  {
    name: 'South Africa',
    code: 'ZA',
    code3: 'ZAF',
    continent: 'africa',
    capital: 'Pretoria',
    countryCode: '+27',
    isoCode: '710',
    demonym: 'South African',
    currencyCode: 'ZAR',
    languageCodes: ['af', 'en', 'zu', 'xh', 'st', 'tn', 'ts', 'ss', 've', 'nr', 'nd'],
    timezoneCode: 'africa-johannesburg',
  },
  {
    name: 'Egypt',
    code: 'EG',
    code3: 'EGY',
    continent: 'africa',
    capital: 'Cairo',
    countryCode: '+20',
    isoCode: '818',
    demonym: 'Egyptian',
    currencyCode: 'EGP',
    languageCodes: ['ar'],
    timezoneCode: 'africa-cairo',
  },
  {
    name: 'Russia',
    code: 'RU',
    code3: 'RUS',
    continent: 'europe',
    capital: 'Moscow',
    countryCode: '+7',
    isoCode: '643',
    demonym: 'Russian',
    currencyCode: 'RUB',
    languageCodes: ['ru'],
    timezoneCode: 'europe-moscow',
  },
  {
    name: 'South Korea',
    code: 'KR',
    code3: 'KOR',
    continent: 'asia',
    capital: 'Seoul',
    countryCode: '+82',
    isoCode: '410',
    demonym: 'South Korean',
    currencyCode: 'KRW',
    languageCodes: ['ko'],
    timezoneCode: 'asia-seoul',
  },
  {
    name: 'Netherlands',
    code: 'NL',
    code3: 'NLD',
    continent: 'europe',
    capital: 'Amsterdam',
    countryCode: '+31',
    isoCode: '528',
    demonym: 'Dutch',
    currencyCode: 'EUR',
    languageCodes: ['nl'],
    timezoneCode: 'europe-amsterdam',
  },
  {
    name: 'Belgium',
    code: 'BE',
    code3: 'BEL',
    continent: 'europe',
    capital: 'Brussels',
    countryCode: '+32',
    isoCode: '056',
    demonym: 'Belgian',
    currencyCode: 'EUR',
    languageCodes: ['nl', 'fr', 'de'],
    timezoneCode: 'europe-brussels',
  },
  {
    name: 'Switzerland',
    code: 'CH',
    code3: 'CHE',
    continent: 'europe',
    capital: 'Bern',
    countryCode: '+41',
    isoCode: '756',
    demonym: 'Swiss',
    currencyCode: 'CHF',
    languageCodes: ['de', 'fr', 'it', 'rm'],
    timezoneCode: 'europe-zurich',
  },
  {
    name: 'Austria',
    code: 'AT',
    code3: 'AUT',
    continent: 'europe',
    capital: 'Vienna',
    countryCode: '+43',
    isoCode: '040',
    demonym: 'Austrian',
    currencyCode: 'EUR',
    languageCodes: ['de'],
    timezoneCode: 'europe-vienna',
  },
  {
    name: 'Sweden',
    code: 'SE',
    code3: 'SWE',
    continent: 'europe',
    capital: 'Stockholm',
    countryCode: '+46',
    isoCode: '752',
    demonym: 'Swedish',
    currencyCode: 'SEK',
    languageCodes: ['sv'],
    timezoneCode: 'europe-stockholm',
  },
  {
    name: 'Norway',
    code: 'NO',
    code3: 'NOR',
    continent: 'europe',
    capital: 'Oslo',
    countryCode: '+47',
    isoCode: '578',
    demonym: 'Norwegian',
    currencyCode: 'NOK',
    languageCodes: ['no'],
    timezoneCode: 'europe-oslo',
  },
  {
    name: 'Denmark',
    code: 'DK',
    code3: 'DNK',
    continent: 'europe',
    capital: 'Copenhagen',
    countryCode: '+45',
    isoCode: '208',
    demonym: 'Danish',
    currencyCode: 'DKK',
    languageCodes: ['da'],
    timezoneCode: 'europe-copenhagen',
  },
  {
    name: 'Finland',
    code: 'FI',
    code3: 'FIN',
    continent: 'europe',
    capital: 'Helsinki',
    countryCode: '+358',
    isoCode: '246',
    demonym: 'Finnish',
    currencyCode: 'EUR',
    languageCodes: ['fi', 'sv'],
    timezoneCode: 'europe-helsinki',
  },
  {
    name: 'Iceland',
    code: 'IS',
    code3: 'ISL',
    continent: 'europe',
    capital: 'Reykjavik',
    countryCode: '+354',
    isoCode: '352',
    demonym: 'Icelandic',
    currencyCode: 'ISK',
    languageCodes: ['is'],
    timezoneCode: 'atlantic-reykjavik',
  },
  {
    name: 'Ireland',
    code: 'IE',
    code3: 'IRL',
    continent: 'europe',
    capital: 'Dublin',
    countryCode: '+353',
    isoCode: '372',
    demonym: 'Irish',
    currencyCode: 'EUR',
    languageCodes: ['en', 'ga'],
    timezoneCode: 'europe-dublin',
  },
  {
    name: 'Portugal',
    code: 'PT',
    code3: 'PRT',
    continent: 'europe',
    capital: 'Lisbon',
    countryCode: '+351',
    isoCode: '620',
    demonym: 'Portuguese',
    currencyCode: 'EUR',
    languageCodes: ['pt'],
    timezoneCode: 'europe-lisbon',
  },
  {
    name: 'Greece',
    code: 'GR',
    code3: 'GRC',
    continent: 'europe',
    capital: 'Athens',
    countryCode: '+30',
    isoCode: '300',
    demonym: 'Greek',
    currencyCode: 'EUR',
    languageCodes: ['el'],
    timezoneCode: 'europe-athens',
  },
  {
    name: 'Poland',
    code: 'PL',
    code3: 'POL',
    continent: 'europe',
    capital: 'Warsaw',
    countryCode: '+48',
    isoCode: '616',
    demonym: 'Polish',
    currencyCode: 'PLN',
    languageCodes: ['pl'],
    timezoneCode: 'europe-warsaw',
  },
  {
    name: 'Turkey',
    code: 'TR',
    code3: 'TUR',
    continent: 'asia',
    capital: 'Ankara',
    countryCode: '+90',
    isoCode: '792',
    demonym: 'Turkish',
    currencyCode: 'TRY',
    languageCodes: ['tr'],
    timezoneCode: 'europe-istanbul',
  },
  {
    name: 'Thailand',
    code: 'TH',
    code3: 'THA',
    continent: 'asia',
    capital: 'Bangkok',
    countryCode: '+66',
    isoCode: '764',
    demonym: 'Thai',
    currencyCode: 'THB',
    languageCodes: ['th'],
    timezoneCode: 'asia-bangkok',
  },
  {
    name: 'Vietnam',
    code: 'VN',
    code3: 'VNM',
    continent: 'asia',
    capital: 'Hanoi',
    countryCode: '+84',
    isoCode: '704',
    demonym: 'Vietnamese',
    currencyCode: 'VND',
    languageCodes: ['vi'],
    timezoneCode: 'asia-ho-chi-minh',
  },
  {
    name: 'Indonesia',
    code: 'ID',
    code3: 'IDN',
    continent: 'asia',
    capital: 'Jakarta',
    countryCode: '+62',
    isoCode: '360',
    demonym: 'Indonesian',
    currencyCode: 'IDR',
    languageCodes: ['id'],
    timezoneCode: 'asia-jakarta',
  },
  {
    name: 'Malaysia',
    code: 'MY',
    code3: 'MYS',
    continent: 'asia',
    capital: 'Kuala Lumpur',
    countryCode: '+60',
    isoCode: '458',
    demonym: 'Malaysian',
    currencyCode: 'MYR',
    languageCodes: ['ms'],
    timezoneCode: 'asia-kuala-lumpur',
  },
  {
    name: 'Singapore',
    code: 'SG',
    code3: 'SGP',
    continent: 'asia',
    capital: 'Singapore',
    countryCode: '+65',
    isoCode: '702',
    demonym: 'Singaporean',
    currencyCode: 'SGD',
    languageCodes: ['en', 'ms', 'ta', 'zh'],
    timezoneCode: 'asia-singapore',
  },
  {
    name: 'Philippines',
    code: 'PH',
    code3: 'PHL',
    continent: 'asia',
    capital: 'Manila',
    countryCode: '+63',
    isoCode: '608',
    demonym: 'Filipino',
    currencyCode: 'PHP',
    languageCodes: ['tl', 'en'],
    timezoneCode: 'asia-manila',
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    code3: 'NZL',
    continent: 'oceania-australia',
    capital: 'Wellington',
    countryCode: '+64',
    isoCode: '554',
    demonym: 'New Zealander',
    currencyCode: 'NZD',
    languageCodes: ['en', 'mi'],
    timezoneCode: 'pacific-auckland',
  },
  {
    name: 'Chile',
    code: 'CL',
    code3: 'CHL',
    continent: 'south-america',
    capital: 'Santiago',
    countryCode: '+56',
    isoCode: '152',
    demonym: 'Chilean',
    currencyCode: 'CLP',
    languageCodes: ['es'],
    timezoneCode: 'america-santiago',
  },
  {
    name: 'Peru',
    code: 'PE',
    code3: 'PER',
    continent: 'south-america',
    capital: 'Lima',
    countryCode: '+51',
    isoCode: '604',
    demonym: 'Peruvian',
    currencyCode: 'PEN',
    languageCodes: ['es', 'qu', 'ay'],
    timezoneCode: 'america-lima',
  },
  {
    name: 'Colombia',
    code: 'CO',
    code3: 'COL',
    continent: 'south-america',
    capital: 'Bogotá',
    countryCode: '+57',
    isoCode: '170',
    demonym: 'Colombian',
    currencyCode: 'COP',
    languageCodes: ['es'],
    timezoneCode: 'america-bogota',
  },
  {
    name: 'Venezuela',
    code: 'VE',
    code3: 'VEN',
    continent: 'south-america',
    capital: 'Caracas',
    countryCode: '+58',
    isoCode: '862',
    demonym: 'Venezuelan',
    currencyCode: 'VES',
    languageCodes: ['es'],
    timezoneCode: 'america-caracas',
  },
  {
    name: 'Ecuador',
    code: 'EC',
    code3: 'ECU',
    continent: 'south-america',
    capital: 'Quito',
    countryCode: '+593',
    isoCode: '218',
    demonym: 'Ecuadorian',
    currencyCode: 'USD',
    languageCodes: ['es'],
    timezoneCode: 'america-guayaquil',
  },
  {
    name: 'Uruguay',
    code: 'UY',
    code3: 'URY',
    continent: 'south-america',
    capital: 'Montevideo',
    countryCode: '+598',
    isoCode: '858',
    demonym: 'Uruguayan',
    currencyCode: 'UYU',
    languageCodes: ['es'],
    timezoneCode: 'america-montevideo',
  },
  {
    name: 'Paraguay',
    code: 'PY',
    code3: 'PRY',
    continent: 'south-america',
    capital: 'Asunción',
    countryCode: '+595',
    isoCode: '600',
    demonym: 'Paraguayan',
    currencyCode: 'PYG',
    languageCodes: ['es', 'gn'],
    timezoneCode: 'america-asuncion',
  },
  {
    name: 'Bolivia',
    code: 'BO',
    code3: 'BOL',
    continent: 'south-america',
    capital: 'Sucre',
    countryCode: '+591',
    isoCode: '068',
    demonym: 'Bolivian',
    currencyCode: 'BOB',
    languageCodes: ['es', 'qu', 'ay'],
    timezoneCode: 'america-la-paz',
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    code3: 'SAU',
    continent: 'asia',
    capital: 'Riyadh',
    countryCode: '+966',
    isoCode: '682',
    demonym: 'Saudi',
    currencyCode: 'SAR',
    languageCodes: ['ar'],
    timezoneCode: 'asia-riyadh',
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    code3: 'ARE',
    continent: 'asia',
    capital: 'Abu Dhabi',
    countryCode: '+971',
    isoCode: '784',
    demonym: 'Emirati',
    currencyCode: 'AED',
    languageCodes: ['ar'],
    timezoneCode: 'asia-dubai',
  },
  {
    name: 'Israel',
    code: 'IL',
    code3: 'ISR',
    continent: 'asia',
    capital: 'Jerusalem',
    countryCode: '+972',
    isoCode: '376',
    demonym: 'Israeli',
    currencyCode: 'ILS',
    languageCodes: ['he', 'ar'],
    timezoneCode: 'asia-jerusalem',
  },
  {
    name: 'Qatar',
    code: 'QA',
    code3: 'QAT',
    continent: 'asia',
    capital: 'Doha',
    countryCode: '+974',
    isoCode: '634',
    demonym: 'Qatari',
    currencyCode: 'QAR',
    languageCodes: ['ar'],
    timezoneCode: 'asia-qatar',
  },
  {
    name: 'Kuwait',
    code: 'KW',
    code3: 'KWT',
    continent: 'asia',
    capital: 'Kuwait City',
    countryCode: '+965',
    isoCode: '414',
    demonym: 'Kuwaiti',
    currencyCode: 'KWD',
    languageCodes: ['ar'],
    timezoneCode: 'asia-kuwait',
  },
  {
    name: 'Bahrain',
    code: 'BH',
    code3: 'BHR',
    continent: 'asia',
    capital: 'Manama',
    countryCode: '+973',
    isoCode: '048',
    demonym: 'Bahraini',
    currencyCode: 'BHD',
    languageCodes: ['ar'],
    timezoneCode: 'asia-bahrain',
  },
  {
    name: 'Oman',
    code: 'OM',
    code3: 'OMN',
    continent: 'asia',
    capital: 'Muscat',
    countryCode: '+968',
    isoCode: '512',
    demonym: 'Omani',
    currencyCode: 'OMR',
    languageCodes: ['ar'],
    timezoneCode: 'asia-muscat',
  },
  {
    name: 'Jordan',
    code: 'JO',
    code3: 'JOR',
    continent: 'asia',
    capital: 'Amman',
    countryCode: '+962',
    isoCode: '400',
    demonym: 'Jordanian',
    currencyCode: 'JOD',
    languageCodes: ['ar'],
    timezoneCode: 'asia-amman',
  },
  {
    name: 'Lebanon',
    code: 'LB',
    code3: 'LBN',
    continent: 'asia',
    capital: 'Beirut',
    countryCode: '+961',
    isoCode: '422',
    demonym: 'Lebanese',
    currencyCode: 'LBP',
    languageCodes: ['ar', 'fr'],
    timezoneCode: 'asia-beirut',
  },
  {
    name: 'Syria',
    code: 'SY',
    code3: 'SYR',
    continent: 'asia',
    capital: 'Damascus',
    countryCode: '+963',
    isoCode: '760',
    demonym: 'Syrian',
    currencyCode: 'SYP',
    languageCodes: ['ar'],
    timezoneCode: 'asia-damascus',
  },
  {
    name: 'Iraq',
    code: 'IQ',
    code3: 'IRQ',
    continent: 'asia',
    capital: 'Baghdad',
    countryCode: '+964',
    isoCode: '368',
    demonym: 'Iraqi',
    currencyCode: 'IQD',
    languageCodes: ['ar', 'ku'],
    timezoneCode: 'asia-baghdad',
  },
  {
    name: 'Iran',
    code: 'IR',
    code3: 'IRN',
    continent: 'asia',
    capital: 'Tehran',
    countryCode: '+98',
    isoCode: '364',
    demonym: 'Iranian',
    currencyCode: 'IRR',
    languageCodes: ['fa'],
    timezoneCode: 'asia-tehran',
  },
  {
    name: 'Pakistan',
    code: 'PK',
    code3: 'PAK',
    continent: 'asia',
    capital: 'Islamabad',
    countryCode: '+92',
    isoCode: '586',
    demonym: 'Pakistani',
    currencyCode: 'PKR',
    languageCodes: ['ur', 'en'],
    timezoneCode: 'asia-karachi',
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    code3: 'BGD',
    continent: 'asia',
    capital: 'Dhaka',
    countryCode: '+880',
    isoCode: '050',
    demonym: 'Bangladeshi',
    currencyCode: 'BDT',
    languageCodes: ['bn'],
    timezoneCode: 'asia-dhaka',
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    code3: 'LKA',
    continent: 'asia',
    capital: 'Colombo',
    countryCode: '+94',
    isoCode: '144',
    demonym: 'Sri Lankan',
    currencyCode: 'LKR',
    languageCodes: ['si', 'ta'],
    timezoneCode: 'asia-colombo',
  },
  {
    name: 'Chad',
    code: 'TD',
    code3: 'TCD',
    continent: 'africa',
    capital: 'N\'Djamena',
    countryCode: '+235',
    isoCode: '148',
    demonym: 'Chadian',
    currencyCode: 'XAF',
    languageCodes: ['fr', 'ar'],
    timezoneCode: 'africa-ndjamena',
  },
  {
    name: 'Grenada',
    code: 'GD',
    code3: 'GRD',
    continent: 'north-america',
    capital: 'St. George\'s',
    countryCode: '+1-473',
    isoCode: '308',
    demonym: 'Grenadian',
    currencyCode: 'XCD',
    languageCodes: ['en'],
    timezoneCode: 'america-grenada',
  },
  {
    name: 'Antigua and Barbuda',
    code: 'AG',
    code3: 'ATG',
    continent: 'north-america',
    capital: 'St. John\'s',
    countryCode: '+1-268',
    isoCode: '028',
    demonym: 'Antiguan',
    currencyCode: 'XCD',
    languageCodes: ['en'],
    timezoneCode: 'america-antigua',
  },
  {
    name: 'Tonga',
    code: 'TO',
    code3: 'TON',
    continent: 'oceania-australia',
    capital: 'Nuku\'alofa',
    countryCode: '+676',
    isoCode: '776',
    demonym: 'Tongan',
    currencyCode: 'TOP',
    languageCodes: ['to', 'en'],
    timezoneCode: 'pacific-tongatapu',
  },
]
