// Comprehensive language data based on ISO 639-1, ISO 639-2, and major world languages
// Sources: 
// - https://github.com/lorenanda/world-languages/blob/master/languages-and-dialects-geo.csv
// - https://github.com/JovianHQ/opendatasets/blob/master/data/countries-languages-spoken/countries-languages.csv

export const languagesData = [
  // Major World Languages (by number of speakers)
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'zh', name: 'Chinese (Mandarin)', nativeName: '中文 (普通话)' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'yue', name: 'Chinese (Cantonese)', nativeName: '粵語' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
  { code: 'ko', name: 'Korean', nativeName: '한국어' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'or', name: 'Oriya', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'my', name: 'Burmese', nativeName: 'မြန်မာဘာသာ' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands' },
  
  // European Languages
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip' },
  { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն' },
  { code: 'eu', name: 'Basque', nativeName: 'Euskara' },
  { code: 'be', name: 'Belarusian', nativeName: 'Беларуская' },
  { code: 'bs', name: 'Bosnian', nativeName: 'Bosanski' },
  { code: 'br', name: 'Breton', nativeName: 'Brezhoneg' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Български' },
  { code: 'ca', name: 'Catalan', nativeName: 'Català' },
  { code: 'co', name: 'Corsican', nativeName: 'Corsu' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk' },
  { code: 'et', name: 'Estonian', nativeName: 'Eesti' },
  { code: 'fo', name: 'Faroese', nativeName: 'Føroyskt' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi' },
  { code: 'gl', name: 'Galician', nativeName: 'Galego' },
  { code: 'ka', name: 'Georgian', nativeName: 'ქართული' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar' },
  { code: 'is', name: 'Icelandic', nativeName: 'Íslenska' },
  { code: 'ga', name: 'Irish', nativeName: 'Gaeilge' },
  { code: 'lv', name: 'Latvian', nativeName: 'Latviešu' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių' },
  { code: 'lb', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch' },
  { code: 'mk', name: 'Macedonian', nativeName: 'Македонски' },
  { code: 'mt', name: 'Maltese', nativeName: 'Malti' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk' },
  { code: 'nn', name: 'Norwegian Nynorsk', nativeName: 'Norsk nynorsk' },
  { code: 'nb', name: 'Norwegian Bokmål', nativeName: 'Norsk bokmål' },
  { code: 'oc', name: 'Occitan', nativeName: 'Occitan' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română' },
  { code: 'rm', name: 'Romansh', nativeName: 'Rumantsch' },
  { code: 'gd', name: 'Scottish Gaelic', nativeName: 'Gàidhlig' },
  { code: 'sr', name: 'Serbian', nativeName: 'Српски' },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina' },
  { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska' },
  { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg' },
  
  // African Languages
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans' },
  { code: 'ak', name: 'Akan', nativeName: 'Akan' },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ' },
  { code: 'bm', name: 'Bambara', nativeName: 'Bamanankan' },
  { code: 'ee', name: 'Ewe', nativeName: 'Eʋegbe' },
  { code: 'ff', name: 'Fulah', nativeName: 'Fulfulde' },
  { code: 'ha', name: 'Hausa', nativeName: 'Hausa' },
  { code: 'ig', name: 'Igbo', nativeName: 'Igbo' },
  { code: 'kg', name: 'Kongo', nativeName: 'Kikongo' },
  { code: 'lg', name: 'Ganda', nativeName: 'Luganda' },
  { code: 'ln', name: 'Lingala', nativeName: 'Lingála' },
  { code: 'lu', name: 'Luba-Katanga', nativeName: 'Kiluba' },
  { code: 'mg', name: 'Malagasy', nativeName: 'Malagasy' },
  { code: 'nd', name: 'Northern Ndebele', nativeName: 'isiNdebele' },
  { code: 'nr', name: 'Southern Ndebele', nativeName: 'isiNdebele' },
  { code: 'ny', name: 'Chichewa', nativeName: 'Chichewa' },
  { code: 'om', name: 'Oromo', nativeName: 'Afaan Oromoo' },
  { code: 'rn', name: 'Kirundi', nativeName: 'Ikirundi' },
  { code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda' },
  { code: 'sn', name: 'Shona', nativeName: 'chiShona' },
  { code: 'so', name: 'Somali', nativeName: 'Soomaali' },
  { code: 'st', name: 'Southern Sotho', nativeName: 'Sesotho' },
  { code: 'ss', name: 'Swati', nativeName: 'siSwati' },
  { code: 'ti', name: 'Tigrinya', nativeName: 'ትግርኛ' },
  { code: 'tn', name: 'Tswana', nativeName: 'Setswana' },
  { code: 'ts', name: 'Tsonga', nativeName: 'Xitsonga' },
  { code: 'tw', name: 'Twi', nativeName: 'Twi' },
  { code: 've', name: 'Venda', nativeName: 'Tshivenḓa' },
  { code: 'wo', name: 'Wolof', nativeName: 'Wolof' },
  { code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu' },
  
  // Asian Languages
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan' },
  { code: 'bh', name: 'Bihari', nativeName: 'भोजपुरी' },
  { code: 'bo', name: 'Tibetan', nativeName: 'བོད་སྐད་' },
  { code: 'dv', name: 'Divehi', nativeName: 'ދިވެހި' },
  { code: 'dz', name: 'Dzongkha', nativeName: 'རྫོང་ཁ' },
  { code: 'fil', name: 'Filipino', nativeName: 'Filipino' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית' },
  { code: 'jv', name: 'Javanese', nativeName: 'Basa Jawa' },
  { code: 'kk', name: 'Kazakh', nativeName: 'Қазақша' },
  { code: 'km', name: 'Khmer', nativeName: 'ភាសាខ្មែរ' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'कॉशुर' },
  { code: 'ku', name: 'Kurdish', nativeName: 'Kurdî' },
  { code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргызча' },
  { code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ' },
  { code: 'mn', name: 'Mongolian', nativeName: 'Монгол' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'ps', name: 'Pashto', nativeName: 'پښتو' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्' },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල' },
  { code: 'tg', name: 'Tajik', nativeName: 'Тоҷикӣ' },
  { code: 'tk', name: 'Turkmen', nativeName: 'Türkmen' },
  { code: 'tl', name: 'Tagalog', nativeName: 'Tagalog' },
  { code: 'uz', name: 'Uzbek', nativeName: 'Oʻzbek' },
  { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש' },
  
  // Pacific Languages
  { code: 'bi', name: 'Bislama', nativeName: 'Bislama' },
  { code: 'ch', name: 'Chamorro', nativeName: 'Chamoru' },
  { code: 'fj', name: 'Fijian', nativeName: 'Vosa Vakaviti' },
  { code: 'haw', name: 'Hawaiian', nativeName: 'ʻŌlelo Hawaiʻi' },
  { code: 'mh', name: 'Marshallese', nativeName: 'Kajin M̧ajeļ' },
  { code: 'mi', name: 'Maori', nativeName: 'Te Reo Māori' },
  { code: 'sm', name: 'Samoan', nativeName: 'Gagana Samoa' },
  { code: 'to', name: 'Tongan', nativeName: 'Lea fakatonga' },
  { code: 'ty', name: 'Tahitian', nativeName: 'Reo Tahiti' },
  
  // Native American Languages
  { code: 'ay', name: 'Aymara', nativeName: 'Aymar aru' },
  { code: 'cr', name: 'Cree', nativeName: 'ᓀᐦᐃᔭᐍᐏᐣ' },
  { code: 'gn', name: 'Guarani', nativeName: 'Avañe\'ẽ' },
  { code: 'iu', name: 'Inuktitut', nativeName: 'ᐃᓄᒃᑎᑐᑦ' },
  { code: 'kl', name: 'Greenlandic', nativeName: 'Kalaallisut' },
  { code: 'nv', name: 'Navajo', nativeName: 'Diné bizaad' },
  { code: 'oj', name: 'Ojibwe', nativeName: 'ᐊᓂᔑᓈᐯᒧᐎᓐ' },
  { code: 'qu', name: 'Quechua', nativeName: 'Runa Simi' },
  
  // Creoles and Pidgins
  { code: 'ht', name: 'Haitian Creole', nativeName: 'Kreyòl ayisyen' },
  { code: 'pap', name: 'Papiamento', nativeName: 'Papiamentu' },
  { code: 'srn', name: 'Sranan Tongo', nativeName: 'Sranan Tongo' },
  { code: 'tpi', name: 'Tok Pisin', nativeName: 'Tok Pisin' },
  
  // Classical and Liturgical Languages
  { code: 'la', name: 'Latin', nativeName: 'Latina' },
  { code: 'pi', name: 'Pali', nativeName: 'पाऴि' },
  { code: 'chu', name: 'Church Slavonic', nativeName: 'Словѣньскъ' },
  
  // Constructed Languages
  { code: 'eo', name: 'Esperanto', nativeName: 'Esperanto' },
  { code: 'ia', name: 'Interlingua', nativeName: 'Interlingua' },
  { code: 'ie', name: 'Interlingue', nativeName: 'Interlingue' },
  { code: 'vo', name: 'Volapük', nativeName: 'Volapük' },
  
  // Additional Major Regional Languages
  { code: 'ace', name: 'Acehnese', nativeName: 'Bahsa Acèh' },
  { code: 'ban', name: 'Balinese', nativeName: 'ᬩᬲᬩᬮᬶ' },
  { code: 'bug', name: 'Buginese', nativeName: 'ᨅᨔ ᨕᨘᨁᨗ' },
  { code: 'ceb', name: 'Cebuano', nativeName: 'Sinugboanong Binisaya' },
  { code: 'ilo', name: 'Ilokano', nativeName: 'Ilokano' },
  { code: 'min', name: 'Minangkabau', nativeName: 'Baso Minangkabau' },
  { code: 'su', name: 'Sundanese', nativeName: 'Basa Sunda' },
  { code: 'tet', name: 'Tetum', nativeName: 'Tetun' },
  { code: 'war', name: 'Waray', nativeName: 'Winaray' },
  
  // Sign Languages
  { code: 'sgn-us', name: 'American Sign Language', nativeName: 'ASL' },
  { code: 'sgn-gb', name: 'British Sign Language', nativeName: 'BSL' },
  { code: 'sgn-fr', name: 'French Sign Language', nativeName: 'LSF' },
  
  // Additional Languages for specific countries
  { code: 'ber', name: 'Berber', nativeName: 'Tamazight' },
  { code: 'cop', name: 'Coptic', nativeName: 'Ⲙⲉⲧⲣⲉⲙⲛ̀ⲭⲏⲙⲓ' },
  { code: 'fur', name: 'Friulian', nativeName: 'Furlan' },
  { code: 'gsw', name: 'Swiss German', nativeName: 'Schwiizerdütsch' },
  { code: 'lmo', name: 'Lombard', nativeName: 'Lombard' },
  { code: 'lij', name: 'Ligurian', nativeName: 'Ligure' },
  { code: 'lad', name: 'Ladino', nativeName: 'Djudeo-Espanyol' },
  { code: 'mwl', name: 'Mirandese', nativeName: 'Mirandés' },
  { code: 'nap', name: 'Neapolitan', nativeName: 'Napulitano' },
  { code: 'pms', name: 'Piedmontese', nativeName: 'Piemontèis' },
  { code: 'scn', name: 'Sicilian', nativeName: 'Sicilianu' },
  { code: 'srd', name: 'Sardinian', nativeName: 'Sardu' },
  { code: 'vec', name: 'Venetian', nativeName: 'Vèneto' },
  { code: 'wln', name: 'Walloon', nativeName: 'Walon' },
  { code: 'frp', name: 'Arpitan', nativeName: 'Arpetan' },
  { code: 'ang', name: 'Old English', nativeName: 'Ænglisc' },
  { code: 'enm', name: 'Middle English', nativeName: 'Middle English' },
  { code: 'sco', name: 'Scots', nativeName: 'Scots' },
  { code: 'nds', name: 'Low German', nativeName: 'Plattdüütsch' },
  { code: 'vls', name: 'West Flemish', nativeName: 'West-Vlams' },
  { code: 'zea', name: 'Zeelandic', nativeName: 'Zeêuws' },
  { code: 'egl', name: 'Emilian', nativeName: 'Emigliàn' },
  { code: 'ext', name: 'Extremaduran', nativeName: 'Estremeñu' },
  { code: 'lld', name: 'Ladin', nativeName: 'Ladin' },
  { code: 'mfe', name: 'Mauritian Creole', nativeName: 'Kreol Morisien' },
  { code: 'pih', name: 'Norfolk', nativeName: 'Norf\'k' },
  { code: 'rcf', name: 'Réunion Creole', nativeName: 'Kréol Rényoné' },
  { code: 'rup', name: 'Aromanian', nativeName: 'Armãneashti' },
  { code: 'szl', name: 'Silesian', nativeName: 'Ślůnski' },
  { code: 'vec', name: 'Venetian', nativeName: 'Vèneto' },
  { code: 'wls', name: 'Wallisian', nativeName: 'Fakauvea' },
  { code: 'xal', name: 'Kalmyk', nativeName: 'Хальмг' },
  { code: 'sah', name: 'Yakut', nativeName: 'Саха' },
  { code: 'os', name: 'Ossetian', nativeName: 'Ирон' },
  { code: 'kbd', name: 'Kabardian', nativeName: 'Адыгэбзэ' },
  { code: 'ady', name: 'Adyghe', nativeName: 'Адыгабзэ' },
  { code: 'ab', name: 'Abkhazian', nativeName: 'Аҧсуа' },
  { code: 'ba', name: 'Bashkir', nativeName: 'Башҡорт' },
  { code: 'bua', name: 'Buryat', nativeName: 'Буряад' },
  { code: 'ce', name: 'Chechen', nativeName: 'Нохчийн' },
  { code: 'cv', name: 'Chuvash', nativeName: 'Чӑваш' },
  { code: 'dar', name: 'Dargwa', nativeName: 'Дарган' },
  { code: 'inh', name: 'Ingush', nativeName: 'ГӀалгӀай' },
  { code: 'kom', name: 'Komi', nativeName: 'Коми' },
  { code: 'krc', name: 'Karachay-Balkar', nativeName: 'Къарачай-малкъар' },
  { code: 'kum', name: 'Kumyk', nativeName: 'Къумукъ' },
  { code: 'lez', name: 'Lezgian', nativeName: 'Лезги' },
  { code: 'mdf', name: 'Moksha', nativeName: 'Мокшень' },
  { code: 'myv', name: 'Erzya', nativeName: 'Эрзянь' },
  { code: 'sme', name: 'Northern Sami', nativeName: 'Davvisámegiella' },
  { code: 'udm', name: 'Udmurt', nativeName: 'Удмурт' },
  { code: 'alt', name: 'Altai', nativeName: 'Алтай' },
  { code: 'sty', name: 'Siberian Tatar', nativeName: 'Сыбырца' },
  { code: 'tyv', name: 'Tuvan', nativeName: 'Тыва' },
]
