// Timezone data
export const timezonesData = [
  // Americas
  {
    name: 'America/New_York',
    slug: 'america-new-york',
    label: 'Eastern Time (US & Canada)',
    offset: '-05:00',
    offsetMinutes: -300,
    isDST: true,
  },
  {
    name: 'America/Chicago',
    slug: 'america-chicago',
    label: 'Central Time (US & Canada)',
    offset: '-06:00',
    offsetMinutes: -360,
    isDST: true,
  },
  {
    name: 'America/Denver',
    slug: 'america-denver',
    label: 'Mountain Time (US & Canada)',
    offset: '-07:00',
    offsetMinutes: -420,
    isDST: true,
  },
  {
    name: 'America/Los_Angeles',
    slug: 'america-los-angeles',
    label: 'Pacific Time (US & Canada)',
    offset: '-08:00',
    offsetMinutes: -480,
    isDST: true,
  },
  {
    name: 'America/Toronto',
    slug: 'america-toronto',
    label: 'Eastern Time (Canada)',
    offset: '-05:00',
    offsetMinutes: -300,
    isDST: true,
  },
  {
    name: 'America/Vancouver',
    slug: 'america-vancouver',
    label: 'Pacific Time (Canada)',
    offset: '-08:00',
    offsetMinutes: -480,
    isDST: true,
  },
  {
    name: 'America/Mexico_City',
    slug: 'america-mexico-city',
    label: 'Central Time (Mexico)',
    offset: '-06:00',
    offsetMinutes: -360,
    isDST: true,
  },
  {
    name: 'America/Sao_Paulo',
    slug: 'america-sao-paulo',
    label: 'Brasília Time',
    offset: '-03:00',
    offsetMinutes: -180,
    isDST: false,
  },
  {
    name: 'America/Argentina/Buenos_Aires',
    slug: 'america-argentina-buenos-aires',
    label: 'Argentine Time',
    offset: '-03:00',
    offsetMinutes: -180,
    isDST: false,
  },
  {
    name: 'America/Santiago',
    slug: 'america-santiago',
    label: 'Chile Time',
    offset: '-03:00',
    offsetMinutes: -180,
    isDST: true,
  },
  {
    name: 'America/Lima',
    slug: 'america-lima',
    label: 'Peru Time',
    offset: '-05:00',
    offsetMinutes: -300,
    isDST: false,
  },
  {
    name: 'America/Bogota',
    slug: 'america-bogota',
    label: 'Colombia Time',
    offset: '-05:00',
    offsetMinutes: -300,
    isDST: false,
  },
  {
    name: 'America/Caracas',
    slug: 'america-caracas',
    label: 'Venezuelan Time',
    offset: '-04:00',
    offsetMinutes: -240,
    isDST: false,
  },
  {
    name: 'America/Guayaquil',
    slug: 'america-guayaquil',
    label: 'Ecuador Time',
    offset: '-05:00',
    offsetMinutes: -300,
    isDST: false,
  },
  {
    name: 'America/Montevideo',
    slug: 'america-montevideo',
    label: 'Uruguay Time',
    offset: '-03:00',
    offsetMinutes: -180,
    isDST: false,
  },
  {
    name: 'America/Asuncion',
    slug: 'america-asuncion',
    label: 'Paraguay Time',
    offset: '-03:00',
    offsetMinutes: -180,
    isDST: true,
  },
  {
    name: 'America/La_Paz',
    slug: 'america-la-paz',
    label: 'Bolivia Time',
    offset: '-04:00',
    offsetMinutes: -240,
    isDST: false,
  },
  {
    name: 'America/Grenada',
    slug: 'america-grenada',
    label: 'Atlantic Time',
    offset: '-04:00',
    offsetMinutes: -240,
    isDST: false,
  },
  {
    name: 'America/Antigua',
    slug: 'america-antigua',
    label: 'Atlantic Time',
    offset: '-04:00',
    offsetMinutes: -240,
    isDST: false,
  },

  // Europe
  {
    name: 'Europe/London',
    slug: 'europe-london',
    label: 'British Time',
    offset: '+00:00',
    offsetMinutes: 0,
    isDST: true,
  },
  {
    name: 'Europe/Dublin',
    slug: 'europe-dublin',
    label: 'Irish Time',
    offset: '+00:00',
    offsetMinutes: 0,
    isDST: true,
  },
  {
    name: 'Europe/Lisbon',
    slug: 'europe-lisbon',
    label: 'Western European Time',
    offset: '+00:00',
    offsetMinutes: 0,
    isDST: true,
  },
  {
    name: 'Europe/Paris',
    slug: 'europe-paris',
    label: 'Central European Time',
    offset: '+01:00',
    offsetMinutes: 60,
    isDST: true,
  },
  {
    name: 'Europe/Berlin',
    slug: 'europe-berlin',
    label: 'Central European Time',
    offset: '+01:00',
    offsetMinutes: 60,
    isDST: true,
  },
  {
    name: 'Europe/Rome',
    slug: 'europe-rome',
    label: 'Central European Time',
    offset: '+01:00',
    offsetMinutes: 60,
    isDST: true,
  },
  {
    name: 'Europe/Madrid',
    slug: 'europe-madrid',
    label: 'Central European Time',
    offset: '+01:00',
    offsetMinutes: 60,
    isDST: true,
  },
  {
    name: 'Europe/Amsterdam',
    slug: 'europe-amsterdam',
    label: 'Central European Time',
    offset: '+01:00',
    offsetMinutes: 60,
    isDST: true,
  },
  {
    name: 'Europe/Brussels',
    slug: 'europe-brussels',
    label: 'Central European Time',
    offset: '+01:00',
    offsetMinutes: 60,
    isDST: true,
  },
  {
    name: 'Europe/Zurich',
    slug: 'europe-zurich',
    label: 'Central European Time',
    offset: '+01:00',
    offsetMinutes: 60,
    isDST: true,
  },
  {
    name: 'Europe/Vienna',
    slug: 'europe-vienna',
    label: 'Central European Time',
    offset: '+01:00',
    offsetMinutes: 60,
    isDST: true,
  },
  {
    name: 'Europe/Stockholm',
    slug: 'europe-stockholm',
    label: 'Central European Time',
    offset: '+01:00',
    offsetMinutes: 60,
    isDST: true,
  },
  {
    name: 'Europe/Oslo',
    slug: 'europe-oslo',
    label: 'Central European Time',
    offset: '+01:00',
    offsetMinutes: 60,
    isDST: true,
  },
  {
    name: 'Europe/Copenhagen',
    slug: 'europe-copenhagen',
    label: 'Central European Time',
    offset: '+01:00',
    offsetMinutes: 60,
    isDST: true,
  },
  {
    name: 'Europe/Helsinki',
    slug: 'europe-helsinki',
    label: 'Eastern European Time',
    offset: '+02:00',
    offsetMinutes: 120,
    isDST: true,
  },
  {
    name: 'Europe/Athens',
    slug: 'europe-athens',
    label: 'Eastern European Time',
    offset: '+02:00',
    offsetMinutes: 120,
    isDST: true,
  },
  {
    name: 'Europe/Warsaw',
    slug: 'europe-warsaw',
    label: 'Central European Time',
    offset: '+01:00',
    offsetMinutes: 60,
    isDST: true,
  },
  {
    name: 'Europe/Istanbul',
    slug: 'europe-istanbul',
    label: 'Turkey Time',
    offset: '+03:00',
    offsetMinutes: 180,
    isDST: false,
  },
  {
    name: 'Europe/Moscow',
    slug: 'europe-moscow',
    label: 'Moscow Time',
    offset: '+03:00',
    offsetMinutes: 180,
    isDST: false,
  },
  {
    name: 'Atlantic/Reykjavik',
    slug: 'atlantic-reykjavik',
    label: 'Greenwich Mean Time',
    offset: '+00:00',
    offsetMinutes: 0,
    isDST: false,
  },

  // Asia
  {
    name: 'Asia/Dubai',
    slug: 'asia-dubai',
    label: 'Gulf Standard Time',
    offset: '+04:00',
    offsetMinutes: 240,
    isDST: false,
  },
  {
    name: 'Asia/Riyadh',
    slug: 'asia-riyadh',
    label: 'Arabia Standard Time',
    offset: '+03:00',
    offsetMinutes: 180,
    isDST: false,
  },
  {
    name: 'Asia/Jerusalem',
    slug: 'asia-jerusalem',
    label: 'Israel Time',
    offset: '+02:00',
    offsetMinutes: 120,
    isDST: true,
  },
  {
    name: 'Asia/Qatar',
    slug: 'asia-qatar',
    label: 'Arabia Standard Time',
    offset: '+03:00',
    offsetMinutes: 180,
    isDST: false,
  },
  {
    name: 'Asia/Kuwait',
    slug: 'asia-kuwait',
    label: 'Arabia Standard Time',
    offset: '+03:00',
    offsetMinutes: 180,
    isDST: false,
  },
  {
    name: 'Asia/Bahrain',
    slug: 'asia-bahrain',
    label: 'Arabia Standard Time',
    offset: '+03:00',
    offsetMinutes: 180,
    isDST: false,
  },
  {
    name: 'Asia/Muscat',
    slug: 'asia-muscat',
    label: 'Gulf Standard Time',
    offset: '+04:00',
    offsetMinutes: 240,
    isDST: false,
  },
  {
    name: 'Asia/Amman',
    slug: 'asia-amman',
    label: 'Eastern European Time',
    offset: '+02:00',
    offsetMinutes: 120,
    isDST: true,
  },
  {
    name: 'Asia/Beirut',
    slug: 'asia-beirut',
    label: 'Eastern European Time',
    offset: '+02:00',
    offsetMinutes: 120,
    isDST: true,
  },
  {
    name: 'Asia/Damascus',
    slug: 'asia-damascus',
    label: 'Eastern European Time',
    offset: '+02:00',
    offsetMinutes: 120,
    isDST: true,
  },
  {
    name: 'Asia/Baghdad',
    slug: 'asia-baghdad',
    label: 'Arabia Standard Time',
    offset: '+03:00',
    offsetMinutes: 180,
    isDST: false,
  },
  {
    name: 'Asia/Tehran',
    slug: 'asia-tehran',
    label: 'Iran Time',
    offset: '+03:30',
    offsetMinutes: 210,
    isDST: true,
  },
  {
    name: 'Asia/Karachi',
    slug: 'asia-karachi',
    label: 'Pakistan Time',
    offset: '+05:00',
    offsetMinutes: 300,
    isDST: false,
  },
  {
    name: 'Asia/Kolkata',
    slug: 'asia-kolkata',
    label: 'India Standard Time',
    offset: '+05:30',
    offsetMinutes: 330,
    isDST: false,
  },
  {
    name: 'Asia/Dhaka',
    slug: 'asia-dhaka',
    label: 'Bangladesh Time',
    offset: '+06:00',
    offsetMinutes: 360,
    isDST: false,
  },
  {
    name: 'Asia/Colombo',
    slug: 'asia-colombo',
    label: 'Sri Lanka Time',
    offset: '+05:30',
    offsetMinutes: 330,
    isDST: false,
  },
  {
    name: 'Asia/Bangkok',
    slug: 'asia-bangkok',
    label: 'Indochina Time',
    offset: '+07:00',
    offsetMinutes: 420,
    isDST: false,
  },
  {
    name: 'Asia/Ho_Chi_Minh',
    slug: 'asia-ho-chi-minh',
    label: 'Indochina Time',
    offset: '+07:00',
    offsetMinutes: 420,
    isDST: false,
  },
  {
    name: 'Asia/Jakarta',
    slug: 'asia-jakarta',
    label: 'Western Indonesia Time',
    offset: '+07:00',
    offsetMinutes: 420,
    isDST: false,
  },
  {
    name: 'Asia/Kuala_Lumpur',
    slug: 'asia-kuala-lumpur',
    label: 'Malaysia Time',
    offset: '+08:00',
    offsetMinutes: 480,
    isDST: false,
  },
  {
    name: 'Asia/Singapore',
    slug: 'asia-singapore',
    label: 'Singapore Time',
    offset: '+08:00',
    offsetMinutes: 480,
    isDST: false,
  },
  {
    name: 'Asia/Manila',
    slug: 'asia-manila',
    label: 'Philippine Time',
    offset: '+08:00',
    offsetMinutes: 480,
    isDST: false,
  },
  {
    name: 'Asia/Shanghai',
    slug: 'asia-shanghai',
    label: 'China Standard Time',
    offset: '+08:00',
    offsetMinutes: 480,
    isDST: false,
  },
  {
    name: 'Asia/Tokyo',
    slug: 'asia-tokyo',
    label: 'Japan Standard Time',
    offset: '+09:00',
    offsetMinutes: 540,
    isDST: false,
  },
  {
    name: 'Asia/Seoul',
    slug: 'asia-seoul',
    label: 'Korea Standard Time',
    offset: '+09:00',
    offsetMinutes: 540,
    isDST: false,
  },

  // Africa
  {
    name: 'Africa/Cairo',
    slug: 'africa-cairo',
    label: 'Eastern European Time',
    offset: '+02:00',
    offsetMinutes: 120,
    isDST: false,
  },
  {
    name: 'Africa/Johannesburg',
    slug: 'africa-johannesburg',
    label: 'South Africa Standard Time',
    offset: '+02:00',
    offsetMinutes: 120,
    isDST: false,
  },
  {
    name: 'Africa/Ndjamena',
    slug: 'africa-ndjamena',
    label: 'West Africa Time',
    offset: '+01:00',
    offsetMinutes: 60,
    isDST: false,
  },

  // Oceania/Australia
  {
    name: 'Australia/Sydney',
    slug: 'australia-sydney',
    label: 'Australian Eastern Time',
    offset: '+10:00',
    offsetMinutes: 600,
    isDST: true,
  },
  {
    name: 'Australia/Melbourne',
    slug: 'australia-melbourne',
    label: 'Australian Eastern Time',
    offset: '+10:00',
    offsetMinutes: 600,
    isDST: true,
  },
  {
    name: 'Australia/Brisbane',
    slug: 'australia-brisbane',
    label: 'Australian Eastern Time',
    offset: '+10:00',
    offsetMinutes: 600,
    isDST: false,
  },
  {
    name: 'Australia/Perth',
    slug: 'australia-perth',
    label: 'Australian Western Time',
    offset: '+08:00',
    offsetMinutes: 480,
    isDST: false,
  },
  {
    name: 'Pacific/Auckland',
    slug: 'pacific-auckland',
    label: 'New Zealand Time',
    offset: '+12:00',
    offsetMinutes: 720,
    isDST: true,
  },
  {
    name: 'Pacific/Tongatapu',
    slug: 'pacific-tongatapu',
    label: 'Tonga Time',
    offset: '+13:00',
    offsetMinutes: 780,
    isDST: false,
  },
  {
    name: 'Pacific/Fiji',
    slug: 'pacific-fiji',
    label: 'Fiji Time',
    offset: '+12:00',
    offsetMinutes: 720,
    isDST: true,
  },
]
